- .gitignore
- _includes/script.html
- _layouts/about.html
- _layouts/command.html
- _layouts/default.html
- _layouts/doc.html
- _sass/jekyll-theme-midnight.scss
- contribute.md
- When a heading is hovered, a 🔗 symbol appears. Click on it to link to the heading
- When an internal link (e.g. https://www.nushell.sh/installation.html#docker-containers) is clicked, the browser now scrolls to the correct position (previously it scrolled ~60px too far)
- Fix a few HTML issues
- Refactor CSS, convert some colors into Sass variables
- Fix broken link
> Add anchor links to headings, tidy up HTML and Sass

- _includes/script.html
- _sass/fonts.scss
- _sass/jekyll-theme-midnight.scss
- _sass/rouge-base16-dark.scss
This PR adds some JS which iterates over `<code>` blocks within a `<pre>` and replaces all horizontal line characters (`━`, `─`) with a `<u>` elment containing the character.
This element has a CSS rule `width: 1ch` which gives it the width of the `0` character. Unfortunately, this only works in browsers with JS enabled. Furthermore, the `ch` unit is not supported in IE <= 8, Safari <= 6.1, Android Browser <= 4.3 and Opera Mini. In these browsers, this fix has no effect. However, I think this is acceptable, since these browsers are rarely used.
Fixes #11
> Fix variable width characters in `pre`

- _sass/jekyll-theme-midnight.scss
Same change as what was done in 076d63e2d for the `<code>` elements, now applied for the logo as well.
Here's what the website looks for me on Firefox 72.0 on macOS 10.15.2 (Catalina):
Before:
After:
> ![Screenshot 2020-01-17 at 17 51 24](https://user-images.githubusercontent.com/478237/72634249-13c4fd80-3952-11ea-9259-ffe1647baa46.png)
> Fix logo font

- installation.md
- Various wording, punctuation and formatting tweaks
- Add a separate section for Homebrew, since it works for both macOS and Linux
- Break some long lines, especially those with links, to allow for cleaner diffs
> Improve installation instructions

- Gemfile.lock
- _layouts/home.html
- _sass/jekyll-theme-midnight.scss
PR adds os detection to determine which installation instructions to display on the front page. #37
> add os-specific installation instructions to front page

- _config.yml
- _layouts/command.html
- _sass/jekyll-theme-midnight.scss
- _sass/normalize.scss
- commands/00_newtable.txt
- commands/update_commands.py
- documentation.md
- installation.md
This PR was triggered by noticing one of the typos that was fixed in https://github.com/nushell/contributor-book/pull/16 (namely, "contributers" --> "contributors").
> Fix typos and EOL whitespace

- _config.yml
Url is used as `link rel=canonical` in html.
> Fix canonical url

- documentation.md
Simple removal of leftover dashes in the Documentation for `from` and `to` subcommands in order to address [issue #1864 from the main nushell repository](https://github.com/nushell/nushell/issues/1864).
This is the simplest solution. I think the preferred solution would be to remove the subcommands from the list completely and add * to `from` and `to` commands to indicate that these commands have subcommands.
> Remove leftover dash in the `from` and `to` subcommands

- CONTRIBUTING.md
- README.md
- docker-compose.yml
Updated jekyll from 3.8 to 4.0, to match the bundler version in use here (2.1.4; 3.8 ships with 2.0.2)
Removed the matching, Docker-less instructions from the README.
> copy and update CONTRIBUTING.md from the book repo

- _includes/navigation.html
The old blog link takes a while to redirect, a direct link is better. Also use https links, not http. The Let's Encrypt certs are fine.
> navigation: add link to demo, fix link to blog

- installation.md
They probably should still redirect, but that's not working (anymore)
> installation: fix book links

- cookbook/git.md
Replacing the (nu) tag allows removing the quotes from the formatting string.
The new command works in both linux and windows systems.
Discussion in https://github.com/nushell/nushell/issues/2730
> Replace splitting tag in git log

- book/README.md
Coming from Bash occurred twice. I kept the capitalized version.
> remove duplicate line

- snippets/introduction/sys_get_external_echo_example.sh
This example no longer works. Running in 0.24.1 I get:
```
❯ sys | get host.sessions | ^echo $it
error: Variable not in scope
┌─ shell:1:33
│
1 │ sys | get host.sessions | ^echo $it
│                                 ^^^ missing '$it' (note: $it is only available inside of a block)
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:993:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm far from an expert on nushell but I'm hoping that I have intuited what the correct syntax should be.
> Update external echo example to work under 0.24.1

- book/nushell_map.md
`Sort-Object {Get-Random}` was mistakenly listed as a Bash command. It has been moved to the PowerShell column.
> Move PowerShell command listed in Bash column

- book/installation.md
- snippets/installation/pull_prebuilt_container.sh
I made the following changes to the Docker installation instructions.
- Link to Quay.io
- Move the difference of "nu" and "nu-base" to before the run commands
- "dockerfiles provided" -> "provided dockerfiles"
- Changed "Multistage build" to match capitalization I found in this blog post: https://www.docker.com/blog/multi-stage-builds/
- I changed the order of the `pull_prebuilt_container.sh` to match the other instructions on the paragraph (everything else first does an example for "nu-base", then "nu", and now that matches)
I realize a lot of documentation is just personal preferences / styles, so feel free to reject some / all of these changes! I just saw some things that I would have done differently.
> clear up docker installation instructions

- book/custom_commands.md
Currently, it seems this information is only available [in the source code](https://github.com/nushell/nushell/blob/56adc7c3c6c8c011c2db9cdcf780d9213a925a8b/crates/nu-parser/src/parse/def/primitives.rs#L162-L185).
The mentioned version 0.28.0 will get obsolete soon but I'd guess better than nothing, unless there is some mechanism to keep this up to date automatically.
> Add list of accepted parameter types

- book/README.md
- book/table_of_contents.md
I'm not sure while both README.md and table_of_contents.md are needed, but it seems that they should match. This PR changes them so they do.
> modified README.md and table_of_contents.md to match

- book/coming_from_bash.md
- es/book/llegando_de_bash.md
- ja/book/coming_from_bash.md
The "coming from bash" page for all three languages (en/es/ja) shows `ls -f` as the nu equivalent of the vanilla `la -la`. As of 0.29.0, `ls -f` doesn't seem to exist, but `ls -la` gets you both the long form and shows hidden files.
> update ls -f -> ls -la

- book/configuration.md
`STARSHIP_SHELL` seems to be the magic key to getting rid of the garbled output when using starship prompt in some situations. Add it to the docs so that it is findable by users
> Update starship prompt integration

- snippets/introduction/sys_get_external_echo_example.sh
- snippets/introduction/sys_get_nested_example.sh
Hello! 
The type of sys.host.sessions was changed from a string to a table in this
PR: https://github.com/nushell/nushell/pull/2954, this PR updates the examples in the introduction to reflect that. :)
> update update `sys_get_` examples

- book/working_with_lists.md
Some examples were broken on "Working with lists" page.
> Fix list examples

- book/configuration.md
Hi! :sparkles: 
While going through the configuration documentation, I noticed that 2 configuration options were missing a value type annotation: `completion_prompt_limit` and `true_color`. This PR adds them in to be consistent with the other config option documentation.
> Fix missing value types for completion_prompt_limit and true_color

- book/configuration.md
As noted on nushell/nushell#1843, this option shouldn't be on root. I discovered it while I was configuring my shell :laughing: I decided to move from fish and the case-insensitive option feels much better.
> docs(configuration): show `completion_match_method` under `line_editor`

- book/plugins.md
`nushell` had already used the `main` as the default branch instead of `master`.
> fix(plugin): missing branch

- book/configuration.md
It was brought up in this issue: https://github.com/nushell/nushell/issues/3911 that `config path` is not mentioned on the configuration page. This PR adds this info in the first paragraph to help new users.
> Adding config path argument to first paragraph of configuration.md file

- book/coming_from_bash.md
- book/environment.md
- es/book/llegando_de_bash.md
- ja/book/coming_from_bash.md
* Describe `unlet-env`
* Describe `let-env ENVVAR = $nothing`
* Add `let-env` as example of `export` and `unset` in Bash table
I could only update the Bash tables in the translated books.
> Document removing environment variables

- book/coming_from_bash.md
Signed-off-by: Tw <tw19881113@gmail.com>
> Add equivalent for `>>` in bash and fix a documentation issue in save

- book/coming_from_bash.md
It seems github's markdown parser have different behavior for the backslash in code block than the website's:
github's default parser works fine:
but the website shows the additional backslash in the table:
Because the website is our target eventually, so I remove the additional backslash.
> remove additional backslash

- blog/2019-11-05-nushell-0_5_0.md
I was trying to set configs in nu 0.37 and noticed this error. I can't check, but I suspect (?) the instructions were meant to be as PRed for 0.7.2 (and that these changes haven't been introduced later)?
> Fix typo in "config set" instructions

- zh-cn/README.md
Update README.md with Chinese Translations
> Update README.md with Chinese Translations

- book/environment.md
Some very minor grammatical changes to environment.md...
> small fixes in environment.md

- README.md
- book/installation.md
The instructions to install nushell using Winget referenced an incorrect
package name nu.
Updates made to the website and book documentation to reflect the
correct package name nushell.
Resolves nushell/nushell.github.io#246
> Correct Winget installation instructions

- README.md
- book/installation.md
Add installation instructions for `Nushell` on Windows using the [Chocolatey](https://chocolatey.org/) package manager.
The project `README.md` and the installation section of the book have been updated to provide package installation instructions using the [Chocolatey](https://chocolatey.org/) package manager.
Resolves #247
> Add installation instructions using Chocolatey

- book/custom_commands.md
Earlier today I was trying to replace part of a pipeline with a helper function. It took me a little while to figure it out, and somehow I bounced off [the documentation](https://www.nushell.sh/book/custom_commands.html#output) without fully understanding it.
- Make it extra clear that the docs are referring to pipeline input/output. This should be obvious on a close read but I think I misunderstood it on a quick skim.
- Rewrite the pipeline input example for `engine-q`; it no longer works on `main` because `each` expects a parameter.
I initially tried to keep the exact functionality of the `my-echo` example but Nushell has changed enough to make that difficult; if you just add an `|it|` parameter it parses but the function incorrectly returns a list of lists:
So instead I just copied the …
> Update command input/output docs

- book/operators.md
Adding some info to cover the basics of case sensitivity. I think case-insensitive comparisons are a common thing to do and this is worth documenting on the operators page, just let me know if I should put this info elsewhere.
> Add case sensitivity section to operators page

- book/scripts.md
I was looking at this page and was confused by this line cause I couldn't search "Command groups" page neither by "Command" nor by "group".
After that I came across https://www.nushell.sh/book/types_of_data.html#groups, and thought it would be useful to show the link instead of the ambiguous expression.
> Show link to Groups setion

- book/3rdpartyprompts.md
- book/coloring_and_theming.md
- book/configuration.md
- book/creating_errors.md
- book/custom_commands.md
- book/dataframes.md
- book/environment.md
- book/installation.md
- book/loading_data.md
- book/moving_around.md
- book/nushell_operator_map.md
- book/parallelism.md
- book/plugins.md
- book/stdout_stderr_exit_codes.md
- book/strings.md
- book/table_of_contents.md
- book/variables_and_subexpressions.md
- book/working_with_lists.md
I read through the Nu book (not including the individual command pages) and fixed up places with incorrect grammar, incorrect spelling, or awkward wording. As discussed [on Discord](https://discord.com/channels/601130461678272522/729071784321876040/950098216597225472) I also normalized the capitalization of "Nushell" where necessary.
I noticed a few other functional things to clean up in the book, I'll submit another PR for those later.
> Nu book: grammar + spelling pass

- book/math.md
- book/variables_and_subexpressions.md
- book/working_with_lists.md
Remove mentions of "math mode" from the Nu Book. Move the "Short-hand math mode" section from the Math page to the Variables and Subexpressions page, rename it "Short-hand subexpressions".
When I read through the Nu Book I was confused by 2 mentions of "math mode". [Here](https://github.com/nushell/nushell.github.io/blob/d9839a5819d74ab99770c7ecfd3881ccd9eecaa2/book/working_with_lists.md?plain=1#L48) it's mentioned in a way that is not reflected in the following example, and [here](https://github.com/nushell/nushell.github.io/blob/d9839a5819d74ab99770c7ecfd3881ccd9eecaa2/book/math.md?plain=1#L76) it's mentioned but only in the context of "short-hand math mode".
JT explained some of the historical context, and it sounds like math mode is a bit less salient to users these days:
> it's …
> Remove math mode mentions, move short hand syntax documentation

- book/installation.md
Closes #63 .
As mentioned in [the `rustup` docs](https://rust-lang.github.io/rustup/installation/windows.html), the VS Build Tools are an OK substitute for anyone who doesn't want all of Visual Studio.
The optional install needed for Rust etc. is called "Desktop development with C++" these days:
> Update Windows build-from-source requirements

- book/configuration.md
- book/types_of_data.md
Hopefully this is the last of the `each` examples that need to be updated with a block parameter.
> Add remaining missing block parameters

- book/working_with_lists.md
Lots of examples on the Working with Lists page that needed to be updated. The descriptions of `each` and `reduce` also needed to be updated to reflect changes to block parameters.
Note: the `empty?` examples are currently broken, I raised an issue: https://github.com/nushell/nushell/issues/4786
> Update working_with_lists for latest Nu

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .vuepress/config.js
- package.json
A few website updates:
- Upgrade GitHub Actions to Node 16 (from 12). 16 is the latest LTS release and 12 will be unsupported soon.
- Upgrade VuePress minor version
- Install the VuePress [back-to-top](https://vuepress.vuejs.org/plugin/official/plugin-back-to-top.html) and [medium-zoom](https://vuepress.vuejs.org/plugin/official/plugin-medium-zoom.html) plugins; they were previously causing build warnings because they were enabled but not installed.
- [Exclude the old Nu book from search results](https://vuepress.vuejs.org/plugin/official/plugin-search.html#test); it was making the search results a lot worse (so many duplicates!)
Manual testing: clicked around the website, confirmed that the search works as expected in both English and German, confirmed that the VuePress plugins now work. …
> Node+VuePress TLC

- book/escaping.md
From an exchange on nu's discord; I wasn't sure what "escaping" meant and was informed that it works by using `PATH`. Jt used this internal/external language to differentiate the two.
> elaborate on escaping details

- book/working_with_lists.md
Fixing some examples that are currently broken on `main` (due to breaking changes in `reduce -n`, the deprecation of `insert`, and mandatory block parameters).
> Update lists page for latest Nu

- .vuepress/config.js
- package.json
As requested in #85, adding RSS/Atom/JSON feeds for the Nu blog.
I looked around and it seems like [vuepress-plugin-feed](https://github.com/webmasterish/vuepress-plugin-feed) is the most popular RSS plugin for VuePress. The documentation wasn't great but it was fairly easy to install.
After adding this, the website build output includes 3 new files: `feed.atom`, `feed.json`, and `rss.xml`. Example: [feeds.zip](https://github.com/nushell/nushell.github.io/files/8229031/feeds.zip). They can be accessed at https://www.nushell.sh/feed.atom etc.
The feeds are _not_ yet linked to from the website; will add links later once I'm 100% confident the feeds are working as expected in production.
> Add RSS feed for blog

- .vuepress/config.js
- package.json
Use algolia as a search provider.
> Switch search provider

- book/installation.md
Making some changes to the installation page, which I previously found a bit confusing.
- Split the install instructions into 3 top-level sections: "Pre-built binaries", "Package managers", "Build from source"
- Add the repology.org badge showing all package managers
- Clarify that crates.io is building from source (IMO this is not obvious to Rust newcomers)
- Move the Windows Terminal instructions to their own section down below (avoids cluttering the main install instructions)
> Nu Book: Reorganize installation page

- .vuepress/config.js
[The WASM demo](http://nushell.sh/demo) is a little out of date (v0.38), and it's looking like it won't get updated before the v0.60 release. Let's remove the prominent link to the demo for now, it'll help avoid some user confusion.
> Remove link to demo until it's updated

- book/configuration.md
- book/environment.md
I noticed that the Environment page was a little out of date (it referred to an `env` section in config that no longer exists). Fixed that up and also did some other cleanup while I was in the area (added links, added an example to the Configuration page, etc.).
> Update env var docs for latest Nu

- book/make_docs.nu
The script is now working on the book side of the world....
Meaning in a couple of days if it appears to be stable we can delete
https://github.com/nushell/nushell/tree/main/docs/commands
> move make_docs.nu from nushell to the book

- blog/README.md
Closes #85. The RSS+Atom feeds added in https://github.com/nushell/nushell.github.io/pull/276 seem good in my RSS reader, adding links at the top of the blog page:
https://www.nushell.sh/rss.xml
https://www.nushell.sh/feed.atom
> Add links to RSS+Atom feeds

- book/README.md
- book/command_reference.md
It occurred to me that we don't really mention `help commands` in a place where a new user reading the docs would stumble across it. Fixing that.
> Book: mention `help commands`

- .vuepress/config.js
- book/coloring_and_theming.md
- book/line_editor.md
- book/thinking_in_nushell.md
- book/working_with_strings.md
An initial pass at organizing the book pages better, as suggested in #295. Also tweaked some page names for consistency.
> Organize book pages by section

- book/command_reference.md
- de/book/command_reference.md
- ja/book/command_reference.md
- pt-BR/book/command_reference.md
I noticed that the commands on the command reference page are *mostly* ordered alphabetically but not always. Moving them into an explicitly-sorted [computed property](https://vuejs.org/guide/essentials/computed.html) to fix that.
It would be cool if JS had a less clunky way to sort by a property, but AFAIK this is the most concise way to do it.
> Sort commands alphabetically

- book/scripts.md
Adding some info about the `source` command and shebangs to the book.
Was initially going to hold off until some discussions about `source` run their course, but changed my mind - happy to revisit these docs later if `source` functionality changes.
> Mention source + shebangs on Scripts page

- blog/2022-03-22-nushell_0_60.md
Hi!
I just tried out the examples in the release blog post. I got an error on the smart `cd` example because of a missing parameter for looping. See the example below and the patch for the blog post.
```
/home/stefano/〉version                                                                                           03/23/2022 08:33:09 AM
╭────────────────────┬─────────────────────────────────────╮
│ version            │ 0.60.0                              │
│ build_os           │ linux-x86_64                        │
│ rust_version       │ rustc 1.59.0 (9d1b2106e 2022-02-23) │
│ rust_channel       │ stable-x86_64-unknown-linux-gnu     │
│ cargo_version      │ cargo 1.59.0 (49d8809dc 2022-02-10) │
│ pkg_version        │ 0.60.0                              │
│ build_time         │ …
```
> Fix Scoped `cd` example in 0.60 release blog post

- book/README.md
- book/thinking_in_nushell.md
I found two minor typos in the beginning of the book. 
Also, I wanted to try to clarify the `Parsing and evaluation...` section of `Thinking in Nu` because I think this is by far the most confusing section for people coming to Nu. I know there have been discussions of how to clarify it on Discord, but I figured I'd submit some minor changes as a first effort.
---
Personally, I think that the given example is more confusing than is necessary. This is especially true because if you run each line as a separate command in the shell, it will work perfectly - and this is how most people will think to try the script. 
Instead, I would highlight the second example and use that to explain the overall concept. It's much more clear (to me, at least) that sourcing a dynamic path doesn't work because …
> Fix minor typos and clarify `Parsing and evaluation...` section

- book/nushell_map_functional.md
Fix broken table rendering for epub book, Read https://github.com/nushell/nushell.github.io/issues/199 for more detail
> Fix broken table rendering for epub book, close #199

- book/3rdpartyprompts.md
This PR adds instruction for setting the session key that is used for deduplicating log messages and correct some typos. 
By the way, what is `hide PROMPT_COMMAND_RIGHT` supposed to do exactly? It doesn't seem to do anything.
> Starship: add session key instructions & correct typos

- book/coloring_and_theming.md
This PR improves the list of table border options:
- remove duplicate listing of the `rounded` option
- uses a bulleted list instead of a numbered list (since there isn't an order to the options, it's better to use a bulleted list).
> docs: table border options

- .vuepress/config.js
Fixed the wrong gender of the adjective "neue" in the description.
"Art" (species, kind) is female, so it must be "eine **neue** Art"
> docs(german): fix grammar in description

- book/nushell_map.md
- book/nushell_map_functional.md
- book/nushell_map_imperative.md
This PR:
- Adds `str collect` to the three "Nu map from..." tables. This subcommand is named differently from most other languages I'm familiar with (I'm used to it being called something like `join`), so I missed this completely when looking for it. Hopefully this would make it more discoverable.
- Renames the `trim` rows to `str trim`. The `trim` command was [removed a while ago](https://github.com/nushell/nushell/pull/2560), so this brings the tables up-to-date with this change.
I think most of `str`'s other subcommands have names very similar to other languages, so I'm not sure they all need to be documented here - but if you think otherwise then I'm happy to add some more too :)
> Add `str collect` to "Nu map from ..." tables, and fix entries for `trim`

- .prettierignore
Disable code formatting for commands' docs
Or, alternatively, you can merge this PR: https://github.com/nushell/nushell.github.io/pull/349
> chore: Ignore formatting the docs for commands

- book/coming_from_bash.md
At version `0.60.0` if you run `ls | where type == Dir` it doesn't return anything. Using the lowercase `dir` works fine.
> book/coming-form-bash: fix type == dir

- book/configuration.md
- de/book/konfiguration.md
The previous instructions did not work, because the first alias would also refer to the system's `open`.
This is not an ideal solution, because we lose the nice help info from Nushell's `open`, but it works.
> Update instructions on aliasing open

- book/3rdpartyprompts.md
- de/book/3rdpartyprompts.md
The Starship docs describe a different way to enable it in Nushell.
The approach described in the Nushell docs didn't work for me, but the one described in the Starship docs did.
> added link to an alternate way to enable Starship

- book/coming_from_bash.md
In Bash, `which` only works on executables; to get information about an alias, function, or built-in, you need to use `type`. Nushell's `which` is therefore more like Bash's `type`.
I'm not sure if the length of the new line justifies reformatting the table so that the end-of-line pipes align again.
> Indicate that `which` works like Bash's `type`

- book/operators.md
Updating the Operators page with info about the regex operator (`=~`, `!~`) changes.
> Document regex operator changes

- book/working_with_strings.md
When first dealing with interpolated strings, I found that I needed to escape some parentheses, and couldn't find any documentation about how to do this. A search in Discord said that there isn't any proper way to do this yet (though please correct me if I'm wrong!)
This PR documents the two ways of working around this that I'm aware of.
> Describe interpolated string escape workarounds

- blog/2022-04-12-nushell_0_61.md
Just a tiny typo in the regex operator things `=~` and `!~`
> Typo fix in 2022-04-12-nushell_0_61.md

- book/working_with_tables.md
New method of concatenating table is now using the `append` command.
This PR aims to document this change accordingly
> Fix "Concatenate tables" section from "Table docs"

- book/configuration.md
Adding a "PATH configuration" section to the "Nu as a shell" -> Configuration page.
This is a bit redundant (can get the same info from a careful read of the Environment page), but I think it's worth making this info more searchable+discoverable; we get a lot of questions about this on Discord.
> Document PATH configuration

- book/aliases.md
This clarifies how to create an alias with pipes...
> update section on aliases for adding pipes and persisting

- book/loading_data.md
- book/types_of_data.md
As per issue #405, there are two pages of the title "Working With Strings". I have changed the first to "Handling Strings" in accordance with the suggestions in the issue and changed the relevant links too.
> Changed the confusing title of "Working With Strings"

- book/coloring_and_theming.md
I was reading the [documentation on prompt configuration](https://www.nushell.sh/book/coloring_and_theming.html#prompt-configuration-and-coloring) and noticed this link didn't _quite_ go to the right place. I think this change will fix that.
> Fix broken nu_scripts repo link

- book/custom_commands.md
- We forgot to mention default parameter values
- Update to use `str collect` for natural string experience
> Mention default values for command parameters.

- .vuepress/config.js
- ja/README.md
This patch updates Japanese translations to the latest english version and translates the rest of content.
> Translate `/ja/README.md` to Japanese

- book/loading_data.md
Previously `open` included syntax highlighting and paging. This has since changed and causes confusion
> Remove outdated reference to `open` pager

- book/nushell_map_functional.md
since `each` can do IO, it’s honestly closer to Haskell’s `mapM`
> book/nushell_map_functional.md: add mapM as Haskell equiv. of each

- .github/workflows/deploy.yml
- book/configuration.md
- de/book/konfiguration.md
Added a section in the documentation for the new config file login.nu (see issue [#4620](https://github.com/nushell/nushell/issues/4620) and PR [#5714](https://github.com/nushell/nushell/pull/5714))
> Add doc fo loginshell file #4620

- book/working_with_lists.md
Fixed example causing type_mismatch in "Iterating over lists" subsection.
resolves #496
> Fixed example causing type_mismatch in working_with_lists.md

- README.md
- de/README.md
- ja/README.md
- zh-CN/README.md
Users no longer need to install the C runtime on Windows: https://github.com/nushell/nushell/pull/5717
P.S. I love that "Windows user" is "Windowsnutzer" in German
> Remove MS CRT info now that we're statically linking it

- README.md
- de/README.md
- ja/README.md
- tr/README.md
- zh-CN/README.md
Fix broken images in README.md
> Fix broken images in README.md

- book/types_of_data.md
I feel this makes it make more sense / more cohesive? / helps new users?
> Links `types_of_data` page to `describe` command

- cookbook/help.md
`false` and `true` are builtin values since 0.60.0 version. Therefore a dollar sign is redundant.
> Fix outdated `$false` value

- README.md
The code blocks are shell sessions and not shell scripts which is why the highlighted oddly (`install` a different color)
---
Out of scope project suggestions:
* Support a mirror on an open source Git forge
* Support an open source communication alternatives like IRC or Matrix
> Syntax highlighting as `console`

- book/variables_and_subexpressions.md
It seemed to suggest that $it was necessary in {|$somevar| $somevar.size > 10kb }.
> Changes misleading example

- book/moving_around.md
Small convenience change that was just bugging me. All the `ls` were hyperlinked, so the other commands should be too.
> Add helpful links

- book/working_with_lists.md
Some of the code examples contained use of `echo` which is not necessary in current Nu. Let's encourage the simplest use possible.
> Update working_with_lists.md (removing unnecessary use of echo)

- README.md
- book/installation.md
I recently talked to someone who wasn't sure how to open Nu after installing it from Homebrew. And fair enough, it's not obvious that you launch it as `nu` when many package managers identify it as `nushell`!
This PR just explains how to launch Nu by typing `nu`.
> Explain how to launch Nu after installing

- book/environment.md
- book/loading_data.md
- de/book/environment.md
- de/book/konfiguration.md
- zh-CN/book/configuration.md
- zh-CN/book/environment.md
In this PR, I have replaced all occurences of some old and broken links to the default config files.
These files are now [default_config.nu](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu) and [default_env.nu](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_env.nu) and the book did not link to these new locations on some pages :confused: 
I've run global pattern searches to make sure:
- I have caught all the bad URLs mentioning one of the two config files in [nushell/nushell.github.io](https://github.com/nushell/nushell.github.io)
- the two files above are correct and the only ones in [nushell/nushell](https://github.com/nushell/nushell)
Hope you'll find that usefull :relieved:
cheers :tada:
> FIX: update the links to the default config files

- .vuepress/config.js
Didn't read the contributing guide, sorry. This should make the direnv section appear in the sidebar of the cookbook.
> Update config.js/cookbook with direnv example

- book/command_reference.md
Hi.
In the previous state. It is hard to know that the command is clickable.
To tell reader (without thinking) that those commands is clickable, they need to have the same color as other clickable item.
> fix: all clickable items should have the same color

- book/operators.md
`**' was listed twice as "exponentiation (power)" and as "pow"
> deduplicate `**' in operators.md

- book/coming_from_bash.md
Stars were incorrectly escaped
> correct escapes in coming_from_bash.md

- book/coming_from_cmd.md
(Just downloaded the new version from winget)
The notable fix is changing `cp <destination> <source>` to `cp <source> <destination>`.
I also went ahead and added an interesting use of cmd `COPY` which I've run into.
> Update coming_from_cmd.md for nu 0.77

- book/coming_to_nu.md
like is done for coming_from_bash. This keeps the chapter page as a complete listing of the chapter contents.
> Mention coming_from_cmd in coming_to_nu

- book/escaping.md
`^external` no longer runs commands through the CMD interpreter, so does not pick up builtins (except for the explicitly allowed ones). Make this more readily apparent.
> Note Windows caveat in Escaping to the System

- book/coming_from_cmd.md
The list doesn't include `PAUSE` or `CLS` despite them [now being allowed](https://github.com/nushell/nushell/pull/6371), as this page currently targets the released version 0.67.
> Note status of calling CMD builtins from Nushell

- book/custom_commands.md
Also removes reference to `123` being a valid command name; although defining it throws no error, it's impossible to call it.
Given the next subsection shows how to define a custom command with spaces in it, this should be fine, just removes ambiguity.
Fixes #566.
> Remove ambiguity about command quotes

- .github/workflows/ci.yml
- .vuepress/config.js
- book/custom_commands.md
- package-lock.json
- package.json
Upgrade  all vuepress plugins and fix doc search navigation by pressing `enter` key
Should fix https://github.com/nushell/nushell.github.io/issues/551
> Upgrade  all vuepress plugins and fix doc search navigation by pressing `enter` key

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .vuepress/config.js
- book/custom_commands.md
- package-lock.json
- package.json
Upgrade all vuepress plugins and fix doc search navigation by pressing `enter` key
> Upgrade all vuepress plugins and fix doc search navigation by pressing `enter` key

- book/types_of_data.md
'Duration' and 'File sizes' sections were incomplete with values missing.
For the duration `1month` I wrote "30 days" for clarification. A month can be anywhere from 28–31 days depending on the month while the program always seems to treat a month as 30 days.
> Update types_of_data.md with missing values

- book/dataframes.md
- book/nushell_map_functional.md
- book/nushell_map_imperative.md
- book/working_with_lists.md
- cookbook/help.md
- de/book/working_with_lists.md
- es/book/mapa_funcional_nushell.md
- ja/book/nushell_map_functional.md
- zh-CN/book/dataframes.md
- zh-CN/book/nushell_map_functional.md
- zh-CN/book/nushell_map_imperative.md
- zh-CN/book/working_with_lists.md
Account for nushell/nushell#6464
`any?`/`all?`/`empty?` to `any`/`all`/`is-empty`
> Update former question mark commands in docs

- book/configuration.md
We get a lot of questions about how to set up PATH for Homebrew. Adding some instructions/examples to the Configuration page.
> Add Homebrew PATH documentation

- book/plugins.md
https://github.com/nushell/nushell/commits/d2e4f03d194361676e406717eeb7a7eeafb28b1f/crates/nu_plugin_python/plugin.py?browsing_rename_history=true&new_path=crates/nu_plugin_python/nu_plugin_python_example.py&original_branch=main
> fix (plugins): python plugin url changed

- book/dataframes.md
- book/loading_data.md
Note on top of the dataframe and database section
Complimentary to #629
> Mention the `--features extra` requirement in the text

- book/pipelines.md
- book/types_of_data.md
Fixes https://github.com/nushell/nushell/issues/6668.
The `groups` section is deprecated.
> add reference to semicolons, remove redundant `group` from types_of_data

- book/3rdpartyprompts.md
- book/commands/input.md
- book/thinking_in_nu.md
- book/variables_and_subexpressions.md
- de/book/thinking_in_nushell.md
- de/book/variablen_und_unterausdruecke.md
- es/book/variables_y_subexpresiones.md
- zh-CN/book/3rdpartyprompts.md
- zh-CN/book/thinking_in_nu.md
- zh-CN/book/variables_and_subexpressions.md
This PR fixes examples using the `-` character in their name, which does not seem to be valid in nu 0.69.1.
I found these occurences with the regexes `let \w+-` and `\$\w+-`, so it's possible I missed something.
> Fix example variables using `-` in their name

- book/variables_and_subexpressions.md
I've faced the relative issue about using subexpression with external commands, and also find that someone else is facing the same problem too: 
Relative: https://github.com/nushell/nushell/issues/5898
Discord message: https://discord.com/channels/601130461678272522/601130461678272524/1022757912130633738
https://discord.com/channels/601130461678272522/614593951969574961/959930011756924959
So I think it's worth to note about it
> Add note about subexpression with external commands

- book/custom_completions.md
Document the ability to return a list of `{value: "", description: ""}` records from a completion function.
context: https://discordapp.com/channels/601130461678272522/958067223187062834/1002353516515442759
> Add documentation for completions with descriptions

- README.md
It's not much but I imported nushell into OpenBSD packages, so the website can now include BSD in the operating system list where it's known to run.
I think it's worth mentioning because it implies nushell is really portable, but as it's too niche I prefered not adding any extra info with regard to installation, and it's already covered by package manager / source install.
> Mention nushell also run on BSD systems

- book/coming_from_bash.md
- book/custom_commands.md
- book/environment.md
- book/hooks.md
- book/nushell_map.md
- book/nushell_map_functional.md
- book/nushell_map_imperative.md
- book/pipelines.md
- book/scripts.md
- book/stdout_stderr_exit_codes.md
- book/thinking_in_nu.md
- book/types_of_data.md
- book/variables_and_subexpressions.md
- book/working_with_lists.md
- book/working_with_strings.md
- contributor-book/plugins.md
Basically none of the given examples actually need `echo`, and they are improved by shortening them or replacing them with bare list `[ ]` syntax.
Also improved readability/accuracy of language comparison tables:
* "All commands" text changed to "relevant commands".
* Removed commands were removed.
* Commands with no data in the other columns were removed due to having no relevant information and making the table needlessly long.
* Some other rows were amended based on my limited experience.
> Simplified examples by removing unneeded `echo` calls

- book/environment.md
Closes https://github.com/nushell/nushell/issues/6733
I understand I could have reworded this to make it clear it works for POSIX only, but I decided to go with this instead because Windows capitalisation is a bit counterintuitive and could do with clarification more.
> Fix let-env Path example to be accurate for Windows

- book/working_with_strings.md
Closes #640.
Also:
* Added section for string operators
* Added 'at a glance' table
* Changed some examples because I feel like self-aggrandising text isn't, on the whole, actually that appealing to the newest of users
> Updated working_with_strings.md (closes #640)

- book/variables_and_subexpressions.md
Hello! I'm learning nushell with the book and I'm blown away so far.
I ran this example code and it seems to me `$my_value.name` returns that column as a list. `.0` is required to get the first element and the desired output.
> Fix variable path expression example

- book/modules.md
Hi, 
This PR tries to add an example usage to the `use` command when we try to export a module's environment. This comes because of discussion in nushell [issue](https://github.com/nushell/nushell/issues/6973). 
I have tried to play along the existing example to reflect what @kubouch taught me, so feel free to modify/add stuff. Thanks:)
> expand docs on using use with export-env

- book/variables_and_subexpressions.md
Reflect to pr: https://github.com/nushell/nushell/pull/7156
It's auto-trimmed for now
> remove `Subexpressions with external commands` session

- book/custom_commands.md
Don't forget to close the tip/warning boxes with `:::`
> Fix tip boxes in `book/custom_commands.md`

- book/dataframes.md
- book/installation.md
- book/loading_data.md
- snippets/installation/build_nu_from_source.sh
- snippets/installation/build_nu_from_source_release.sh
- snippets/installation/build_nu_yourself.sh
- snippets/installation/cargo_install_nu_features_stable.sh
- snippets/installation/cargo_install_nu_more_features.sh
Updating the docs to account for the recent feature changes in https://github.com/nushell/nushell/pull/7182 and https://github.com/nushell/nushell/pull/7180. Don't merge this until v0.72 is out.
> Update docs for dataframe+database feature change

- book/installation.md
Pretty sure the `rawkey` and `clipboard` features are from before engine-q, correct me if I'm wrong.
Leaving the `snippets/installation/use_rawkey_and_clipboard.sh` snippet around because it's still referenced in some translations.
> Remove old features from install instructions

- book/scripts.md
Found a dead link in the book.
It seems that it had not been able to follow up changes in https://github.com/nushell/nushell.github.io/pull/634 .
> Fix dead links

- book/dataframes.md
I think there is a missing negation in sentence “These will allow you to define complex data operations that will
[not] be executed until you decide to "finish" the pipe.”
> Fix error in `book/dataframes.md`

- book/custom_commands.md
hello is a bare string, which cannot appears in command position
> Correct command

- blog/2022-12-20-nushell-0.73.md
I believe we forgot to mention the breaking change to `save` which is already causing us problems: https://github.com/nushell/nushell/pull/7545
Ignore the whitespace changes, I think they were created by the Husky commit hook.
> Mention breaking save change

- blog/2022-12-20-nushell-0.73.md
- fix heading levels
- use shell style consistently
- clarify phrasing on the breaking changes
> Fix styling on 0.73 release notes

- book/line_editor.md
We need a `:` instead of `=` in this line.
> Fix syntax error for menu

- book/make_docs.nu
- package.json
* Certain hard-coded commands' `extra_usage` is wrapped in code block markup to prevent their code from being interpreted as markdown, instead of every command's `extra_usage` being wrapped.
* No longer deletes files due to erasing platform-specific commands.
* Notes now appear before parameters, in accordance with the actual nu `help`.
* Added task to `package.json` to run it.
~~Also reran make_docs.nu.~~
> Fixed various issues in make_docs.nu

- .vuepress/configs/sidebar/en.ts
- book/README.md
- book/design_notes.md
- book/how_nushell_code_gets_run.md
Adds a new Design Notes chapter with a section about how Nushell code gets run.
> Start Design Notes chapter; Add parse-eval notes

- blog/2019-08-23-introducing-nushell.md
Should close #741.
This PR removes a broken link to the "plugins chapter" from the first paragraph of the [_Plugins_ section in _Introducing nushell_](https://www.nushell.sh/blog/2019-08-23-introducing-nushell.html#plugins):
- https://book.nushell.sh/en/plugins is dead and should not be accessed, as discussed in #741
maybe we should do one of the following?
- remove the whole "_There's more information in the plugins chapters._" sentence
- keep that sentence but link to the "_plugins_" page at https://www.nushell.sh/book/plugins.html, until the contributors book is up and online again
you tell me :wink:
> remove a broken link in "Introducing nushell" # "Plugins"

- book/explore.md
This should close #742.
As agreed in #742, this PR simply links the "`default-config.nu`" text from the [`explore` page](https://www.nushell.sh/book/explore.html#config) to the [`default-config.nu`](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu) file of the source base of `nushell` :+1:
> link to default config file in the "explore" page

- .vuepress/styles/index.scss
Demo using the [latest blog post](https://www.nushell.sh/blog/2023-01-10-nushell_0_74.html) (at the time of writing) as an example.
Before:
After:
CC @hustcer who did a lot of work in the Vuepress setup in #465.
Also CC @Aloso who did similar tweaks back in #8 + #9.
> Add two style tweaks to improve tables in code blocks

- book/installation.md
https://github.com/nushell/nushell/commit/9d0e52b94d1e9df079308e7c9ea32cd76b7ac0ea bumps the required rust version to 1.66.1.
> Update rust version requirement in installation

- .vuepress/configs/sidebar/en.ts
- book/default_shell.md
- book/installation.md
- Adds instructions to add Nu to your terminal
- Advises against setting Nu as login shell
Heavily inspired by
https://elv.sh/get/#using-elvish-as-your-default-shell
> Add separate page for setting Nu as default shell

- book/loading_data.md
- de/book/loading_data.md
Fix statement about `lines` output type, which is a `list`, not a `table`.
This fixes it in the original English and in the German translation. Other translations contain the same error, but will have to be fixed in separate changes, as I don't know them well enough.
> fix statement about `lines` output type ("table"→"list")

- book/line_editor.md
This PR provides a fix from changing `Ctrl+x` to `Ctrl+r` on the [Reedline Page](https://www.nushell.sh/book/line_editor.html#completion-menu). This fix addresses this [issue](https://github.com/nushell/nushell.github.io/issues/737).
> Fix changed history command to match default in config

- book/commands/par-each.md
- book/thinking_in_nu.md
- book/working_with_lists.md
- de/book/thinking_in_nushell.md
- de/book/working_with_lists.md
- zh-CN/book/thinking_in_nu.md
- zh-CN/book/working_with_lists.md
This PR addresses this [issue](https://github.com/nushell/nushell.github.io/issues/774). The docs were still using `each -n` so I have updated it to use `enumerate | each` as seen in the newest version of Nushell.
> Fix: updating pages that used each -n command

- book/working_with_lists.md
- de/book/working_with_lists.md
- zh-CN/book/working_with_lists.md
fix `all` and `any` usage examples, close #758
> fix `all` and `any` usage examples, close #758

- es/book/cargando_datos.md
Fix statement about `lines` output type, which is a `list`, not a `table`.
This should fix it in the Spanish translation. See PR #764 for a fix of the same problem in the English original and in the German translation.
I don't really know Spanish. I simply looked up the term to use in [Tipos de datos→Listas](https://www.nushell.sh/es/book/tipos_de_datos.html#listas) (and in [Tipos de datos→ Datos estructurados](https://www.nushell.sh/es/book/tipos_de_datos.html#datos-estructurados) where it occurs in singular, albeit not referring to the data type), so it's quite possible I'm introducing grammatical errors.
> [es] fix statement about `lines` output type ("tabla"→"lista")

- pt-BR/book/carregando_dados.md
Fix statement about `lines` output type, which is a `list`, not a `table`.
This should fix it in the Brazilian Portuguese translation. See PR #764 for a fix of the same problem in the English original and in the German translation.
I don't really know Portuguese. I simply looked up the term to use in [Tipos de dados→Listas](https://www.nushell.sh/pt-BR/book/tipos_de_dados.html#listas) (and in [Tipos de dados→Dados estruturados](https://www.nushell.sh/pt-BR/book/tipos_de_dados.html#dados-estruturados) where it occurs in singular, albeit not referring to the data type), so it's quite possible I'm introducing grammatical errors.
> [pt-BR] fix statement about `lines` output type ("tabela"→"lista")

- book/dataframes.md
- book/nushell_operator_map.md
- cookbook/git.md
- es/book/instalacion.md
- es/book/mapa_operador_nushell.md
- ja/book/nushell_operator_map.md
- pt-BR/book/instalacao.md
- snippets/installation/build_nu_from_source.sh
- snippets/installation/build_nu_from_source_release.sh
- zh-CN/book/dataframes.md
- zh-CN/book/nushell_operator_map.md
hello there :wave: :yum: 
i did notice, in the installation page, that there were remaining mentions to the old and deprecated `&&` and `||` operators
> **Note**
> this is what we get now
> ```bash
> >_ true && true
> Error: nu::parser::shell_andand
> 
>   × The '&&' operator is not supported in Nushell
>    ╭─[entry #12:1:1]
>  1 │ true && true
>    ·      ─┬
>    ·       ╰── instead of '&&', use ';' or 'and'
>    ╰────
>   help: use ';' instead of the shell '&&', or 'and' instead of the boolean
>         '&&'
> ```
> and
> ```bash
> >_ false || true
> Error: nu::parser::shell_oror
> 
>   × The '||' operator is not supported in Nushell
>    ╭─[entry #13:1:1]
>  1 │ false || true
>    ·       ─┬
>    ·        ╰── instead of '||', use 'try' or 'or'
>    ╰────
>   help: use 'try' instead of …
```
> FIX: remove mentions to old and deprecated `&&` and `||` logic operators

- book/coming_from_bash.md
The documentation states that `$env.PATH` lets the user quote "See the current path". This is not what happens though, the command errors out.
```
❯ $env.PATH
Error: nu::shell::name_not_found (link)
× Name not found
╭─[entry #16:1:1]
1 │ $env.PATH
·      ──┬─
·        ╰── did you mean 'Path'?
╰────
```
<details><summary>Screenshot</summary>
</details>
The correct command *in Windows* to get the current path is `$env.Path`, not `$env.PATH`.
> Rename $env.PATH to $env.Path to reflect actual shell behavior

- book/thinking_in_nu.md
I tried running `each -n` and got an error.
> Remove mention of `-n` on `each`

- make_docs.nu
Related to
- nushell/nushell#8189
- nushell/nushell#8319
As introduced in nushell/nushell#8189 and nushell/nushell#8319, the `$nu.scope.commands` structure now holds the `result`s of the command `example`s :+1: 
in order to generate accurate documentation pages, the `make_docs.nu` script needs to use `$nu.scope.commands.example.result` in addition to `$nu.scope.commands.example.description` and `$nu.scope.commands.example.example`
this PR uses `$example.result` in the `command-doc` command right after the `> ($example.example)` line, adding the result to the page.
> **Note**
> in order to print real structured data, i could not use `$example.result` only, e.g. it would print raw string data even with tables...
> the easiest i found was to `try` to `--expand` the `$example.result` and …
> add the example results to the documentation pages

- make_docs.nu
hello there :wave: 
i wanted to
- regenerate the website after https://github.com/nushell/nushell/pull/8189
- contribute to the `make_docs.nu` script
however, i had a lot of trouble understanding the script itself and what it was doing...
so i decided i would try to refactor it and add documentation to it :yum: 
> **Warning**
> there are a lot of changes when looking at the full diff...
> this section explains the new look of the scripts and proves that the features of the script did not change :relieved: 
so, in this PR, i've
- fixed the order of the functions, i.e. the `main` at the bottom and more and more general tools to the top of the file, in the order they appear in the script
- fixed the indentation, i.e. from 2 spaces to 4 spaces for readability
- regrouped some commands …
> REFACTOR: add documentation to and clean up the `make_docs.nu` script

- book/custom_completions.md
This PR shows and example of how to use the fish shell complete command to do external completions.
> add fish_completer example

- make_docs.nu
Related to #803.
in #803, i've added the example results to the output of `make_docs.nu`.
however, there are ANSI escape sequences all over the place when the output is a string... :scream: 
this PR removes them by using `ansi strip` when the results are `string`s :+1:
> FIX: remove ANSI escape sequences when the output is a `string`

- book/nushell_map.md
I know nothing about nu, but https://www.nushell.sh/commands/docs/is-empty.html and https://www.nushell.sh/commands/docs/with-env.html spell them with dashes.
> Dashes instead of underscores in command comparisons

- book/quick_tour.md
- commands/README.md
This PR adds a link to the quick tour at the top of the command reference, as prompted by [this Hacker News comment](https://news.ycombinator.com/item?id=35127105).
> Newbie-friendly command reference header

- blog/2023-03-14-nushell_0_77.md
Add description for #8205 and #8014
> Add description for #8205 and #8014

- book/stdout_stderr_exit_codes.md
I presume that these were typos. This commit fixes them.
> Fix typos in book/stdout_stderr_exit_codes.md

- book/custom_completions.md
I saw no reference of this anywhere in the documentation so I propose we add this to the custom completions page. Here's an [example](https://github.com/nushell/nu_scripts/blob/main/kubernetes/kubernetes.nu#L172) of this in the nu_scripts repository which is where I figured out it's possible to do it.
English isn't my first language don't hesitate to correct me on my grammar and phrasing.
> Add context aware custom completions to the book

- de/book/overlays.md
I just went for one version for #815 now.
> DE translation for overlays

- book/custom_completions.md
i love the new "Custom completion" page, it's really great to learn about all that stuff thanks to #836 :relieved: 
i simply thought there could be a little note about `value / description` based completion, about the fact that only the `value` is used in the actual argument when selecting an option :yum:
> add a note about "value / description" completion

- .vuepress/configs/sidebar/de.ts
- de/book/command_signature.md
- i18n-meta.json
I have done another one over the weekend.
But I am curious. The .vuepress/config.js seems to have changed.
Is there somewhere else now, I have to add this to appear on the site?
> DE translation for command_signature

- make_docs.nu
fix #850, make `make_docs.nu` work for nu v0.77.2+
> fix #850, make `make_docs.nu` work for nu v0.77.2+

- blog/2023-04-04-nushell_0_78.md
a little one about nushell/nushell#8511 and nushell/nushell#8570 for better `error make`ing :+1:
> add a note about better `error make`

- blog/2023-04-04-nushell_0_78.md
a little note to explain the new `--indent`, `--tabs` and `--raw` options for outputting NUON data :yum: 
> see nushell/nushell#8366
> add #8366 to the release notes

- blog/2023-03-14-nushell_0_77.md
i had no time to add this before the previous release, so here it is :yum: 
was originally added in https://github.com/nushell/nushell.github.io/pull/847
> add a note about #8189 to the 0.77 release

- cookbook/direnv.md
The Direnv recipe no longer worked on the latest version of Nushell, as the hook syntax has changed from code in a string to using blocks.
This updates the recipe accordingly.
> Update the Direnv recipe to use a block, rather than `code:`

- i18n-meta.json
- i18n.nu
> Fix i18n script for nu v0.78

- book/thinking_in_nu.md
Formatting the asterisk as an inline code block `*` with a `-` dash separator implies that it were a parameter to or syntax to the discussed topic (scope) and mentioned before. However, this is not the case. It is formatted in a misleading manner.
The asterisk seems to be intended as a footnote indicator. But no asterisk exists in the text before, so it does not follow established asterisk footnote practices either.
These issues are solved by removing the asterisk and making it a simple sentence.
To clarify that the paragraph is an additional note the text is formatted in italics.
> Improve misleading text format on note

- book/working_with_strings.md
- de/book/working_with_strings.md
- zh-CN/book/working_with_strings.md
[`str substring` only allows ranges as of 0.78.](https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#ranges-become-the-standard-range-specifier)
Updates the usage examples for `str substring` in working_with_strings.md for all languages.
Doesn't touch old patch notes.
I couldn't find any other instances of this in the repo (regex: `substring.*\d\s*,\s*\d`), nor any problems with `bytes at`.
> Fix ranges in `str substring` examples

- book/dataframes.md
- cookbook/polars_v_pandas_v_nushell.md
- zh-CN/book/dataframes.md
Miscellaneous dataframe-related documentation fixes.
- Updates all `x-df` commands to `dfr x` (see nushell/nushell#7998).
- [Adds missing parentheses around captured command output for `let`.](https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#let-requires-surrounding-parentheses-for-saving-command-output) These were the only instances of such a problem I could find in the entire repo.
> Update dataframe examples

- book/types_of_data.md
This PR adds documentation for the optional cell path member feature added in 0.78: https://nushell.sh/blog/2023-04-04-nushell_0_78.html#optional-cell-path-members-rgwood
> Mention optional cell path members

- book/variables_and_subexpressions.md
> Fix some typos and other nits to the variable documentation

- book/working_with_lists.md
- de/book/working_with_lists.md
Improves the `insert` and `update` examples in working_with_lists.md by showing their results and adding highlighting.
Copied from the zh-CN version.
> Improve `insert` and `update` examples in working_with_lists.md

- blog/2023-04-25-nushell_0_79.md
a Nushell user has reported issues in the changelog about the standard library, here is a quick fix :ok_hand:
> fix the "`std` import" section of the 0.79 changelog

- blog/2023-04-25-nushell_0_79.md
This was reported by @skelly37 in https://discord.com/channels/601130461678272522/988303282931912704/1101797140356935801.
- only the `std` table
- plus some `npm` auto format
> FIX: add prettier `std` commands format in 0.79 changelog

- book/design_notes.md
Link used to point to book/how_nushell_code_gets_run but since both files are in the same directory, specifying the directory **both** files are in breaks it.
> Fixed link in design_notes to how_nushell_code_gets_run

- book/variables_and_subexpressions.md
`######` will cause an error while rendering ebooks, use `#####` instead
Other changes were caused by code formatting
> Fix heading for ebook building

- book/modules.md
this is a very minor refactoring attempt on the *Modules* chapter :relieved: 
cc/ @kubouch 
- use real `Note` and `Warning` blocks
- use code blocks in the *import patterns* section => i find it easier to read by splitting the section in several clear parts like this
> refactor minor things in the modules chapter

- book/loading_data.md
- book/metadata.md
- book/types_of_data.md
- de/book/loading_data.md
- ja/book/loading_data.md
- snippets/introduction/sys_example.sh
- snippets/loading_data/cargo-toml.sh
- snippets/loading_data/rust-lang-feed.sh
- snippets/loading_data/vscode.sh
- snippets/types_of_data/cell-paths.sh
- zh-CN/book/loading_data.md
- zh-CN/book/metadata.md
should fix #917
this PR adds `| table` at the end of pipelines which give folded tables.
this can be ambiguous given the `default_config.nu` which expands the tables automatically with `$env.config.hooks.display_output` :open_mouth: 
with `| table` this is not ambiguous anymore because `| table` overrides the hook :+1: 
> **Note**
> - i've only searched for `{record`, `[table` and `[list`, which are characteristic of a folded table, in the book
> - i've added some cross-language snippets :thinking:
> FIX: add `| table` to folded tables

- book/nushell_map_functional.md
- book/nushell_map_imperative.md
I have updated the tables to show what match is equivalent to in other languages. There are a couple places that I simply removed the references since there was no closely equivalent feature.
> Fix references to match in the "coming from" pages to reflect its current usage in Nu

- contributor-book/plugins.md
Updated `plugins.md` in the Contributor Book to reflect the current API. The page in its current form appears badly out of date. While the Contributor Book is not linked from within the main docs website, https://www.nushell.sh/contributor-book/plugins.html shows up at the top of web searches for terms like "nushell plugin tutorial" and at least confused me.
I know there are Rust and Python example plugins in the Nushell repo, but I appreciated the simplicity of the example that was in the Contributor Book along with the narrative walk through. I just wished it had reflected the current API. This PR aims to fix that.
> update plugins.md in contributor-book

- book/custom_completions.md
trying to fix #922 
cc/ @MrFoxPro
in this PR i've
- fixed the multi-completer example
- fixed some formatting
- used the new `$env.* = ...` syntax to simplify the examples 
does the following work better @MrFoxPro?
```bash
{|spans|
{
$spans.0: { default_completer $spans | from json } # default
ls: { ls_completer $spans | from json }
git: { git_completer $spans | from json }
} | each {|it| do $it}
}
```
> FIX: out of date external completion examples

- .github/workflows/deploy.yml
Update deploy.yml so that the site can be DEPLOYED WITHOUT GH-PAGES branch
A test deploy could be found here: http://hustcer.github.io/
The docs' site will be deployed from the `main` branch here: https://github.com/hustcer/hustcer.github.io
Some configs need to be modified for more detail see [Publishing with a custom GitHub Actions workflow](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow)
> Update deploy.yml so that the site can be DEPLOYED WITHOUT GH-PAGES 

- book/configuration.md
This documentation addresses the discrepancy I found in this issue [Config Editing fails on Windows #9189](https://github.com/nushell/nushell/issues/9189)
> Update Documentation for Configuration.

- cookbook/tables.md
If the merge command is supplied an expression in curly braces, nushell errors out expecting input and argument, to be both record or both table.
Tested on nushell 0.80.0
To reproduce this error, run:
```sh
let first = [[a b]; [1 2]]
let second = [[c d]; [3 4]]
$first | merge { $second }
```
We get:
```
× Pipeline mismatch.
╭─[entry #5:1:1]
1 │ $first | merge { $second }
· ───┬──   ──┬──
·    │       ╰── expected: input, and argument, to be both record or both table
·    ╰── value originates from here
╰────
```
We don't get errors if we use:
```sh
$first | merge $second
```
> Supply table instead of closure to merge command in tables.md

- contributor-book/plugins.md
In my [previous update](https://github.com/nushell/nushell.github.io/pull/921) to the plugin tutorial a number of other issues were flagged as not fixed. I believe this addresses those as well as expands a section on the low-level protocol that I think is helpful for understanding the Python section.
I've learned a lot while working on these docs but I'm still not super familiar with the technology so I'm very open to feedback on this. I think it addresses the issues flagged as unresolved in the earlier PR.
> Modernize and add additional info to plugin tutorial

- book/coloring_and_theming.md
- book/types_of_data.md
- de/book/coloring_and_theming.md
- zh-CN/book/coloring_and_theming.md
- zh-CN/book/types_of_data.md
See also: nushell/nushell#9337, nushell/nushell#9427
To be consistent with nushell, this PR removes mention of ZB and ZiB.
> Remove mentioning ZB and ZiB

- book/working_with_strings.md
`build-string` was removed in https://github.com/nushell/nushell/pull/7144
> Remove reference to `build-string` from `working_with_strings.md`

- book/custom_completions.md
This PR fixes two issues I found while setting up and using custom completions.
The completer in the docs works mostly fine, but when there are no more valid completions (for example, `ls dir/that/does/not/exist<TAB>` or `nu --invalid-flag<TAB>`) it returned an empty string. This wouldn't normally be an issue, as `from json` would throw an error and the default completer kick in. However, `'' | split row (char newline)` returns `['']`, a valid JSON, and the last span of the completion was being deleted.
I fixed these issue avoiding `split row` and using `from tsv` instead, avoiding some manual parsing in the process. I used the `--no-infer` flag as a technicality, because some commit hashes where being returned as a number instead of a string.
I found another error while testing this fix, …
> Fix custom completion scripts

- .github/workflows/command-block.yml
We frequently see PRs that try to fix or improve command docs. As the
pages are autogenerated this is a futile endeavour.
We regularly have to respond to them and close the PR.
Attempt to provide a workflow that will react to PRs that affect the
command docs path and send a comment.
I don't autoclose for now, as the autogenerated still come in as a PR.
> Automate response to PRs trying to update commands

- book/aliases.md
should solve https://github.com/nushell/nushell/discussions/9586 and probably other issues as well
this PR makes it clear how to add an alias to the persistent config in `config.nu`.
> add a more complete example to persist aliases in `config.nu`

- book/operators.md
- de/book/mathematik.md
They have been replaced with `and` and `or`
> Remove `&&` and `||`

- zh-CN/book/plugins.md
fix a broken link in https://www.nushell.sh/zh-CN/book/plugins.html#%E7%A4%BA%E4%BE%8B
> fix a broken link in plugins page in zh-CN

- book/custom_completions.md
- cookbook/external_completers.md
Following #959, this PR tries to better explain how external completers work, how to integrate them and do a showcase of a possible config that leverages some of the provided examples.
I took the liberty of creating a new cookbook page for the examples, as the size of them was getting out of hand. There are probably some things to improve about clarity, wording and the general structure, so let me know if there's anything that needs changing 😁
---
On an unrelated note, I found [this issue](https://github.com/nushell/nushell/issues/9301). In the troubleshooting section of the cookbook I address how to fix it, so I might redirect them to it after merging 🤔
> Expand external completer docs

- .vuepress/configs/sidebar/en.ts
After #984, the cookbook sidebar entry wasn't created. This PR takes care of that 😬
> Add external completers cookbook entry to sidebar

- cookbook/misc.md
this PR hopefully makes the `ssh-agent` example in the cookbook easier to read :innocent: 
i've also removed the note about `ssh-add` as it does not appear to be useful at all :thinking: 
i use this `ssh-agent` everyday without ever running `ssh-add` :confused:
> refactor `ssh-agent` cookbook example

- book/3rdpartyprompts.md
- book/coloring_and_theming.md
- book/coming_from_bash.md
- book/coming_from_cmd.md
- book/configuration.md
- book/environment.md
- book/hooks.md
- book/line_editor.md
- book/modules.md
- book/overlays.md
related to nushell/nushell#9574
this PR moves from using `let-env FOO = ...` to using `$env.FOO = ...` in all the website.
this was an automatic commit, i've simply run the following command :+1: 
```nushell
sd --string-mode "let-env " '$env.' book/**/*
```
cc/ @jntrnr
> replace `let-env FOO = ...` by `$env.FOO = ...`

- book/overlays.md
- de/book/overlays.md
In the tip for `Overlays are Recordable` the text shows how to create a scratch overlay to record changes into before showing a less verbose version using `overlay new`.
However the more verbose version also uses `overlay new` before it's introduced, which I presume is meant to be `overlay use` and this change updates it for the English and German translation. The Chinese translation appears to be what I believe to be the correct usage and the other translations don't seem to have that section yet and have been left alone.
> tweak `overlay new` tip

- book/nu_fundamentals.md
- book/table_of_contents.md
Hi y'all!
Not sure if this is right. I just noticed that the "Command reference" link at the bottom of  is broken.
I tried fixing it - see diff.
However, there seem to be more places, like in the [table of contents](https://github.com/nushell/nushell.github.io/blob/main/book/table_of_contents.md?plain=1#L40). (Edit: table of contents now also fixed in this PR.)
See also [these search results](https://github.com/search?q=repo%3Anushell%2Fnushell.github.io%20command_reference.md&type=code).
Apparently, in some language versions (japanese, brazilian portugese, german, chinese), `/book/command_reference.md` [exists](https://github.com/nushell/nushell.github.io/blob/main/de/book/command_reference.md?plain=1), while in the default (english) version it [does not …
> fix(docs): Link to Command Reference led to HTTP 404

- book/testing.md
This PR updates the examples in the testing section so that they function. With the recent updates to testing, the examples were no longer working. Primarily, they were still recommending the usage of `test_<name>` to recognize tests instead of using the test annotations. Also, the `use` directives were no longer accurate, and could also be condensed. I've updated the example so that it could be copied and run successfully.
> Update testing examples

- snippets/installation/cargo_install_nu_more_features.sh
Update documentation to reflect the requirement for the `--locked` flag when using `cargo install` with the `dataframe` feature.
This problem has been mentioned in the following issues, but was only fixed in the scripts in the nushell repository:
- nushell/nushell#10014
- nushell/nushell#10084
> Use '--locked' in cargo install snippet for dataframe feature

- blog/2023-08-22-nushell_0_84_0.md
Also makes the `str replace` note a separate section with a fix note.
> Break down shoutouts to separate sections

- commands/docs/dfr_var.md
- commands/docs/format.md
- commands/docs/from.md
- commands/docs/into.md
- commands/docs/into_duration.md
- make_docs.nu
Try to add the following features to `make_docs.nu` for docs generation:
Check the [example docs](https://github.com/nushell/nushell.github.io/pull/1009/files) for more detail
**Note:** 
Only a few command docs were updated here as examples, and all the docs will be regenerated after the next release.
> Some improvements to `make_docs.nu`

- book/configuration.md
The book chapter on configuration mentions ^ syntax before the chapter on escapes. I think it'd be helpful to link to that chapter so the reader can learn more if they want to.
> Link to escape when discussing escapes

- book/loading_data.md
The section on http mentions the http get command but the link points to  (probably deprecreated/renamed) fetch instead of http
> Update loading_data.md, correct link to http command

- book/installation.md
The instructions were in the Package Managers section which meant they were easily missed if someone[0] only read as far as the binary download link.
This is a drive-by contribution which I'm unlikely to follow-up on so feel free to make any changes as you see fit.
(For completeness, it might be worth adding this information to the start of the Quick Tour page too: http://www.nushell.sh/book/quick_tour.html )
[0] Me. I'm the someone. :)
> Move launch instructions earlier in page.

- book/configuration.md
I was confused about where Nushell keeps its config files, and I read this page twice trying to figure it out. Somehow I didn't understand that `echo $nu.env-path` was the answer.
Here's my attempt to make the docs a little clearer.
> Clarify how to check config file paths

- book/modules.md
Replaced `greeeting_purpose` (three 'e's) with `greeting_purpose`.
> Fix small typo in modules.md

- book/plugins.md
The contributor book has a great chapter on how plugins work...
However, when reading the plugins chapter in the nushell book there is no reference to it.
You have to search for it to find it...
I added a link to the end of the plugins chapter so people can read more stuff about plugins...
I found the chapter in the contributor book incredibly insightful.
> add a link to the contributor book at the end of the plugins chapter

- cookbook/external_completers.md
This PR modernizes the external completer docs by using `match` instead of `{ ... } | get -i ... | default ...`.
It's:
- Simpler to read and understand
- A nice way to get folks reading the docs to learn about `match` (<3)
- A textbook example of when to use `match`
> Simplify external completer

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
1. Set min required node version to v18.12.0-LTS, as v16 LTS support will goes to end, see: https://endoflife.date/nodejs
2. Upgrade some node modules
3. Upgrade some outdated Github Actions
> Update min required node version and some node modules

- cookbook/external_completers.md
This PR fixes a typo introduced in https://github.com/nushell/nushell.github.io/pull/1049 ✨
> Fix external completers typo

- book/custom_completions.md
Working now on the DE translation. Quite a tough on.
"Eigene Vervollständigungen..." sounds a bit bumpy...
> Typos in custom_completions

- book/working_with_lists.md
Replaces removed `date format` with `format date`.
---
I ran into the following error when following the [working with lists guide](https://www.nushell.sh/book/working_with_lists.html)
```Nushell
~/tmp> $zones | wrap 'Zone' | upsert Time {|it| (date now | date to-timezone $it.Zone | date format '%Y.%m.%d %H:%M')}                               09/10/2023 01:47:31 PM
Error: nu::shell::removed_command
× Removed command: date format
╭─[entry #97:1:1]
1 │ $zones | wrap 'Zone' | upsert Time {|it| (date now | date to-timezone $it.Zone | date format '%Y.%m.%d %H:%M')}
·                                                                                  ─────┬─────
·                                                                                       ╰── 'date format' has been removed from Nushell. …
```
> Update working_with_lists.md - format date

- book/variables_and_subexpressions.md
Replaces unknown `sin` with `sqrt` for the “Variable values” example.
---
I encountered an error in the [Variable values guide](https://www.nushell.sh/book/variables_and_subexpressions.html#variable-values).
```
~> let val = (42 | math sin)                                                                                                                         09/10/2023 01:58:00 PM
Error: nu::parser::extra_positional
× Extra positional argument.
╭─[entry #108:1:1]
1 │ let val = (42 | math sin)
·                      ─┬─
·                       ╰── extra positional argument
╰────
help: Usage: math
```
I chose `math sqrt`, but feel free to edit to any math subcommand.
> Update variables_and_subexpressions.md - remove obsolete section

- book/scripts.md
I found out that `stdin` is not available when running a script with shebang, and after some investigation I found a solution.
> Support for standard input in script with shebang

- cookbook/direnv.md
First of all thanks for the direnv example!
It got me unblocked, but I missed that I couldn't see the path in the list format when I typed `$env.PATH`.
I'm new to nushell, so if there's a better way to do this than the `no_changes` `changes` thing, let me know and I'll change it. I couldn't find like a `$my_thing | is-not-empty`.
> Change direnv example to upload $env.PATH as a list

- blog/2023-09-05-why-uu.md
The blog post that Darren wrote documenting our integration with uutils/coreutils.
Changed to `Draft` until we're ready to post.
> Blog post documenting our integration with uutils

- cookbook/direnv.md
When using `direnv` like the docs indicated I noticed that I no longer had completions for binaries in the `PATH`. Turns out, `direnv` outputs the variables to load as a string (which is normal) and they're being loaded as-is, without undergoing the transformation specified in `$env.ENV_CONVERSIONS`.
The code I changed gets the subset of variables that need to undergo transformation, applies the transformation and merges them with the original values.
I'm not 100% happy with the implementation as it's not that idiomatic, but I couldn't find an easy way to conditionally update a record and returning a new record in the process. I tried the following approaches:
```nushell
$direnv | items {|key, value| ... { $key: $transformed_value } }
```
```nushell
$direnv | items {|key, value| ... { …
```
> Fix direnv not using transformed values

- blog/2023-09-19-nushell_0_85_0.md
This breaks the Const and Accessibility subsections into their own sections and rewords the const section.
Also added call for help porting the const commands.
> Refactor const section

- book/coloring_and_theming.md
Since [this PR](https://github.com/nushell/nushell/pull/10391) to add transient prompts to Nushell was merged, this PR adds some docs on how to use the newly added environment variables to the website.
> Add information on transient prompt

- .vuepress/configs/sidebar/en.ts
- CONTRIBUTING.md
- book/working_with_lists.md
- book/working_with_strings.md
- book/working_with_tables.md
- cookbook/pattern_matching.md
As discussed in https://github.com/nushell/nushell/issues/10486 Some more examples of the various ways to append things to lists/strings/tables would be appreciated. In addition, `str append` was a nice exmaple of how to use `match` and also pattern match on types. 
This PR adds more examples on the appending in the appropriate sections (specifically more on using the ++ operator which was previously not mentioned).
`str append` is also added to the cookbook and expanded upon somewhat. In the linked issue "vectorisation" was also mentioned but I wasn't quite sure how/what part of the `str append` that refers to so I didn't mention that. If someone can explain that part to me and thinks it would be useful to also add, I'd be happy to do so. 
Finally I think instructions on how to add new …
> Expand `append` examples and add `match` example

- .vuepress/configs/sidebar/en.ts
related to
- https://github.com/nushell/nushell.github.io/pull/904
this PR adds the "style guide" page to the book index in the sidebar to the left under the "Programming in Nu" section, hopefully making it visible to everyone :pray: 
i hope this is the way to do it :yum:
> add the "style guide" page to the sidebar

- make_docs.nu
On my machine, that reduces runtime from 34s to 13s
> make_docs: Parallelize command generation

- cookbook/external_completers.md
changed `split words` to `split row " "` because `split words` gets rid of too much. For example, `"-foo__bar baz" | split words` outputs the list `[foo, bar, daz]` while `"-foo__bar baz" | split row " "` outputs `[-foo__bar, baz]`, which is what we want
This was an issue as I was trying to setup completion for zoxide and this code was splitting `__zoxide_z` into `[zoxide, z]`
> fixed alias normalization

- book/configuration.md
if one extends PATH in `env.nu` and start a different shell before launching nu, one might start to collect the same path multiple times in PATH these lines construct the new value (based on home directory and the separator based on the os)
> prevent same entry in $env.PATH

- book/working_with_lists.md
One comment said `total = 96`, where `product = 96` is printed.
> Fix a minor typo in `working_with_lists`

- book/working_with_tables.md
variable was named `second`, but should be named `third` to match the example
> fix variable name

- book/working_with_lists.md
one might start in the middle of the section
the variable scores is defined above
the example might not result the expected results, hence ensuring assignment is done before
> repeat variable assignment

- book/configuration.md
- book/environment.md
- book/plugins.md
- de/README.md
- de/book/environment.md
- ja/README.md
- zh-CN/README.md
- zh-CN/book/environment.md
This should fix at least one part of my naive issue so that we can close it.
> Fixing #460 changing .html links to .md links

- blog/2023-10-17-nushell_0_86.md
by opening PRs against the `release-notes-0.86` branch.
> Release notes for `0.86`

- book/coming_from_bash.md
closes https://github.com/nushell/nushell/issues/10805
This is a very common thing to want to do and isnt documented anywhere that I could find.
I think an addition to this table would be the best way to communicate how to achieve this.
The pipe could go to anything but I chose less as thats the most common destination and it illustrates the point better than using something generic like `command 2>&1 | other_command`
I had to adjust the table width, so you will want to review with "hide whitespace" enabled.
> add translation for bash "command 2>&1 | less"

- book/coloring_and_theming.md
This adds a note on how Reedline’s menus are themed in the chapter dedicated on coloring and theming.
I found myself looking for this information at the wrong place, and thought it was sensible to at least mention it.
> Add a note on theming Reedline’s menus

- book/3rdpartyprompts.md
related to
- https://discord.com/channels/601130461678272522/1167018880108077096/1167018880108077096
i found someone confused about the snippet in the [Starship part of *How to configure 3rd party prompts*](https://www.nushell.sh/book/3rdpartyprompts.html#starship) not working and giving the following error
```nushell
error: unexpected argument '-1' found
Usage: starship prompt [OPTIONS]
For more information, try '--help'.
NOTE:
passed arguments: ["prompt", "--cmd-duration", "276668", "--status", "-1"]
```
when pressing ctrl-c.
i'm using the [official integration with Starship](https://starship.rs/#nushell) and i've never seen that kind of error.
in this PR, i propose to put the official integration with Starship forward by moving its mention above the snippet, in a TIP :relieved:
> put Starship integration forward in prompt chapter

- cookbook/ssh_agent.md
the initial example has a pretty big flaw if simply copy-pased in one's `env.nu`: every time the user opens a new instance of nu it will start a new instance of ssh-agent, which won't exit when nu does
so here's a nushell and two non-nushell ways to achieve a similar result without said flaw
--- 
also the nushell exemple only adds 2-4ms of startup time if the ssh-agent is seen as already running
(R7 5800x & system on nvme)
> Cookbook ssh agent - alternatives fixing zombie agents

- cookbook/direnv.md
related to
- https://github.com/nushell/nu_scripts/pull/628
- https://github.com/direnv/direnv/pull/1175
i propose to update the Direnv hook, as in https://github.com/nushell/nu_scripts/pull/628 and https://github.com/direnv/direnv/pull/1175 :yum: 
i've seen a few people complaining about this hook in the cookbook, so here is both a working and a much simpler hook to run Direnv in Nushell :innocent:
> update the Direnv section in the cookbook

- book/pipelines.md
This pull request provides documentation for the semantics of nushell with regard to command stdout output, specially to address some of the misleading behavior that manifests itself in the issue https://github.com/nushell/nushell/issues/10175.
> Add Pipelines section about stdout output

- blog/2023-10-17-nushell_0_86.md
related to
- https://github.com/nushell/nushell.github.io/pull/1071
this PR
- removes a useless note that points to a link that has the same GIF as locally: see [*Improving the completions in the REPL*](https://www.nushell.sh/blog/2023-10-17-nushell_0_86.html#improving-the-completions-in-the-repl-toc)
- makes all code blocks Nushell code blocks to have syntax highlighting: see [*Before*](https://www.nushell.sh/blog/2023-10-17-nushell_0_86.html#before) and [*After*](https://www.nushell.sh/blog/2023-10-17-nushell_0_86.html#after)
- removes paths to personal directories in the prompts of code blocks:  see [*Before*](https://www.nushell.sh/blog/2023-10-17-nushell_0_86.html#before) and [*After*](https://www.nushell.sh/blog/2023-10-17-nushell_0_86.html#after)
> add a few fixes for the release note of 0.86.0

- book/modules.md
The created completions directory in the example cannot itself be added to NU_LIB_DIRS but it's parent directory instead. In our example we create the directory in $nu.default-config-dir which should be added to NU_LIB_DIRS
> Clarify Dumping files into directory

- blog/2023-11-14-nushell_0_87_0.md
by opening PRs against the `release-notes-0.87.0` branch.
> Release notes for `0.87.0`

- cookbook/README.md
- cookbook/files.md
- cookbook/git.md
- cookbook/help.md
- cookbook/http.md
- cookbook/parsing.md
- cookbook/parsing_git_log.md
- cookbook/pattern_matching.md
- cookbook/polars_v_pandas_v_nushell.md
- cookbook/setup.md
- cookbook/system.md
- cookbook/tables.md
The unified style favours the removal of any prompt indicator such as `>`.
When appropriate I split `nu` blocks and output blocks as well.
And fixed an example in pattern_matching.md
> Unifies all cookbook codeblocks to use the same style.

- cookbook/parsing.md
Add more examples how to conveniently parse tabular text output from legacy shell utils.
> Add `parse` examples to *Parsing*

- book/environment.md
I didn't initially realize the `?` operator existed (there's only two sections in the book about this, both of which are easy to miss!), and originally accomplished this using `$env | get --ignore-errors FOO` as suggested by `help default`. This seems like a common use case for the `?` operator, so I added a little snippet to guide users towards using `?`
> Add a snippet to suggest using the ? operator for environmental variables

- book/coloring_and_theming.md
- book/coming_from_cmd.md
- book/line_editor.md
- cookbook/parsing_git_log.md
- de/book/coloring_and_theming.md
- de/book/working_with_lists.md
- zh-CN/book/coloring_and_theming.md
- zh-CN/book/line_editor.md
- zh-CN/book/working_with_lists.md
I've noticed one of the examples doesn't work because of removed command so I replace usage of it in all the examples with the new one. It's still part of automatically generated documentation but that should be changed in the main nushell repo which should be fixed as well to avoid confusion.
> Replace usage of removed `date format` with `format date` in examples

- cookbook/external_completers.md
In case of an unknown flag somewhere in the span, carapace outputs the last element of the span followed by the string "ERR". If the flag itself is not the last element, the regex won't match the error message. Instead, check the exact expected value.
Test with
```nu
> chmod -x foo<TAB>
```
> Improve workaround for carapace ERR output

- cookbook/jq_v_nushell.md
JSON strings need to be delimited in quotation marks
> Fix jq comparison

- book/command_signature.md
While implementing a custom alias, I found myself unable to provide an explicit command signature as described in the documentation. A bit of crawling the main repo's commit history led to my discovery that the syntax as described in the documentation was indeed outdated.
After a bit of experimentation I was able to discover the correct annotation syntax.
Ideally, in a slightly longer timescale than I am willing to deal with right now, this change shouldn't be needed; I believe the information on this page would serve better integrated with the rest of the documentation. It seems as though it would fit better there after the syntax change.
> Update command signature doc to modern syntax

- book/line_editor.md
I'm fairly sure this should be `history_menu` instead of `help_menu`.
> Typo in history menu section

- zh-CN/book/shells_in_shells.md
Sync the zh-CN shells_in_shells with the main book to avoid misleading behavior.
Small fix but means a lot.
> Sync zh-CN shells_in_shells.

- cookbook/external_completers.md
Hi,
@rsteube and i integrated the cookbook example for alias expansion in carapace rsteube/carapace-bin#2102. We (mostly not me) found, that nushell expands the alias partially and returns for eg `alias gco = git checkout` a span with `[ "gc", "checkout" ]`. Thus, the cookbook example replaces `gc` with `git` and `checkout`.
To replace `gc` only, we added `take 1` to ensure the alias gets replaced with `git`.
Kind regards
Alexander
> external completer: fixed cookbook example to exchange the first span entry only

- commands/docs/from_eml.md
- commands/docs/from_ics.md
- commands/docs/from_ini.md
- commands/docs/from_vcf.md
- make_docs.nu
Resolves #1091
In `make_docs.nu` command page generation section, added a check for the commands from the plugin `nu_plugin_formats` (`from ini` and others) to add a warning box to those pages informing the users they have to install and register the plugin to use those commands. Also added the changes to the generated docs as well.
There might be a small merge conflict with #1183, but it should be easy to resolve.
---
I tried to figure out a way to not hardcode the command names in `make_docs.nu` and I figured out how the `make_docs.nu` could determine if a command was from a plugin, however I couldn't figure out how to determine which plugins the respective commands came from which I figured was important to add. Maybe it could parse the nu script at `$nu.plugin-path`, but that seemed …
> Adding warning to nu_plugin_formats commands

- cookbook/README.md
The docs currently reference a "#cool-oneliners" channel in the Nushell Discord for Nushell oneliners, however, it links to the "#cool-scripts" channel which I presume was previously the "#cool-onliners" channel. Since I presume the name change was to broaden the channel content up to "multiple line" scripts, and it seems like it's not just oneliners anymore, I moved the mention of the channel to the previous paragraph where it's talking about more general scripts.
I replaced the oneliner channel with the oneliner section of the nu_scripts repo instead. (It looks like there are some things in that section that aren't really oneliners, but that's an issue for the nu_shells repo).
Since the given oneliner is supposed to be an example of what's in the nu_scripts oneliner section, I'll also …
> Updating cookbook intro page due to discord channel rename and other editing.

- book/types_of_data.md
Resolves #1191 and resolves #404
Added a section about the middle "step" range parameter, changed it to "sequence of integer or float values", added a tip about creating similar sequences for chars and dates, and added a warning about displaying open ended ranges.
Hopefully the range step section makes sense or at least isn't too confusing. I tried to be careful with how I presented it but it was a bit tricky.
---
After seeing that the range design is still in flux here nushell/nushell#11086, I considered holding off on adding this and waiting until it's more nailed down, however I figured increasing awareness of it might help us get more feedback about the current design. We can always change it when the time comes.
> Adding range related info.

- book/explore.md
commands
```
:config
:show-config
:tweak
```
were removed 
in https://github.com/nushell/nushell/pull/10259
keeping the documentation up to date
> Remove outdated commands from explore.md

- cookbook/external_completers.md
Update `scope`'s syntax to reflect current syntax and match command from above the file.
> Update `scope`'s syntax in external_completers.md

- book/hooks.md
- book/working_with_tables.md
I've been trying out Nu for a while. Some problem I have is that Nu will try to expand the table structure unless I pipe 
it with `table` command. I've looked into [Working with table](https://www.nushell.sh/book/working_with_tables.html) and [Configuration](https://www.nushell.sh/book/configuration.html) on how to change this default behavior without success. I found a solution by accidently finding this nushell/nushell#7292 issues. So I think that we should have some documentation explaining how to configure it more explicitly.
> Add a section describing how to change table outputs

- .vuepress/configs/sidebar/en.ts
- book/control_flow.md
- book/table_of_contents.md
- cookbook/pattern_matching.md
- i18n-meta.json
Resolves #1207
As the title says, it adds a page on control flow in Nu (and fixes a small misspelling on the pattern matching cookbook page I spotted while working on this).
The PR is in draft because I want to read through it again tomorrow with fresh eyes, but otherwise I think it's ready for review.
<details>
<summary>Long screenshot of the page</summary>
</details>
> Adding a page on control flow (and small misspelling)

- book/custom_completions.md
Noticed I was getting an error after updating nushell warning me that auto spreading lists would be deprecated, updated my configuration and thought this change could be reflected in the docs.
> Update custom_completions.md to use new spread operator in carapace example

- book/how_nushell_code_gets_run.md
- book/thinking_in_nu.md
- book/variables_and_subexpressions.md
- book/working_with_strings.md
Since string interpolation at parse time has been merged (https://github.com/nushell/nushell/pull/11562) but it has unexpected behavior for formatting file sizes and datetimes if used before config.nu is loaded (the default config is used instead of your runtime config), this PR adds a note about that to the "Working with strings" page.
The docs do say [here](https://www.nushell.sh/book/how_nushell_code_gets_run.html) that sourcing a *dynamic* path like `source $"($my_path)/common.nu"` isn't possible, but this may be interpreted as meaning that stuff like `const x = "foo"; source $"($x)"` doesn't work too. There are a few different ways (not mutually exclusive) to avoid confusion:
- Adding `let my_path = ...` to show that `my_path` isn't a constant
- Amending "Sourcing a dynamic path" to …
> Add note about string interpolation at parse time

- cookbook/external_completers.md
I tried copying the examples but got errors like
```
163 │     match $spans.0
·                   ▲
·                   ╰── missing match_block
164 │     {
╰────
```
I just got started using nushell so this might be wrong.
> Fix syntax errors

- cookbook/ssh_agent.md
i did a logout on my machine and noticed the SSH agent i took from the book stopped working :open_mouth: 
i fixed it and thought it would be great to update the book :innocent: 
- uses `snake_case` which is i think the convention with Nushell
- uses [do --env](https://github.com/nushell/nushell.github.io/compare/main...amtoine:fix-ssh-snippet?expand=1#diff-e98bd788993dd2508080f08a338ade8ac95c61eda25455a4a5f8aad2a09fde21R29) to avoid leaking internal definitions to the REPL main scope
- defines the SSH agent path in a [cross-platform way](https://github.com/nushell/nushell.github.io/compare/main...amtoine:fix-ssh-snippet?expand=1#diff-e98bd788993dd2508080f08a338ade8ac95c61eda25455a4a5f8aad2a09fde21R31)
- when the SSH agent file is there
- if the process is running => [load the environment …
> update the SSH agent snippet

- blog/2024-02-06-nushell_0_90_0.md
The release notes for `0.90.1` mention a new `into cellpath` command, but it is actually called `into cell-path`.
> Fix typo in `into cell-path` in the 0.90.1 release notes

- book/configuration.md
Hi there, I added the pyenv path setup to the configuration.md.
Here's a asciinema recording to show how it work.
[![asciicast](https://asciinema.org/a/636181.svg)](https://asciinema.org/a/636181)
> Add pyenv path setup to configuration.md

- .vuepress/config.js
- .vuepress/configs/sidebar/en.ts
- contributor-book/plugin_protocol_reference.md
- contributor-book/plugins.md
See nushell/nushell#11911
Fixes the python examples, and goes more in-depth on the protocol with a protocol reference section.
> Add docs for streaming plugin protocol overhaul

- contributor-book/plugin_protocol_reference.md
Noticed a few things that I didn't catch before after reading it again. `"internal_span"` was renamed to `"span"` in the serialized format but that isn't reflected in some of the JSON examples
And there was also one JSON example that was invalid because it didn't include the `"start"` and `"end"` keys
> Fix issues with spans in the JSON examples in the plugin protocol reference

- book/configuration.md
Hi,
I just wasted a few hours looking for a nice way to add multiple paths to `$env.path`. I came up with this, which I quiet like:
```nu
let extra_paths = ['/some/path', '/another/path']
$env.PATH = (($env.PATH | split row (char esep)) ++ $extra_paths)
```
The double `((` might not be the best so feel free to edit.
I think the standard use case of adding values to the `$env.PATH` is "I want to add a list of values to `$env.PATH`", and not "I want to add a single path to my `$env.PATH`". So I think this example is ideal for new users like myself.
I also think having duplicate paths in `$env.PATH`, is not the right thing to be worried about. So I removed that example, to keep things simple.
> Add an example of adding multiple paths

- book/testing.md
The chapter about unit testing is incorrect, as `std testing` is deprecated. I've made small changes that look logical to me. 
Probably, this chapter needs a foreword about the depreciation of the previous version of std and the current status. However, I don't have such details in mind.
Please, feel free to edit or let me know what I should correct anything. Thanks.
> update text to replace `std testing` with `testing.nu`

- book/working_with_tables.md
@devyn had [a good suggestion on Discord](https://discord.com/channels/601130461678272522/729071784321876040/1213932488313933936):
> I think it would be useful to mention / link to the section on cell paths within the 'working with tables' guide
> 
> https://www.nushell.sh/book/types_of_data.html#cell-paths
> https://www.nushell.sh/book/working_with_tables.html
>
> it seems like a lot of people miss the 'optional cell paths' feature - I certainly didn't find out about it until somewhat recently
> Mention cell paths in Working w/ Tables

- cookbook/external_completers.md
should using ...$in in extern command. other wise will cause an error and no result will be returned.
> Fix a bug in zoxide completer

- make_docs.nu
If we sunset the `--features extra` for building Nushell we don't need
to warn in upcoming releases anymore.
Depends on https://github.com/nushell/nushell/pull/12140
cc @hustcer: Does this simplify the command generation enough so that we
don't need a parallel clone of the main repo anymore (you run it
locally, right?)
> Remove feature `extra` detection from make_docs.nu

- .vuepress/configs/sidebar/en.ts
- cookbook/foreign_shell_scripts.md
This originated from a conversation in the Nushell Discord, where I showed a less sophisticated version of this script in the #cool-scripts channel, and was asked to contribute it to the Cookbook.
Next to reviewing the code, please give your honest opinions on the text, and if you want me to change anything, I appreciate the feedback 🙂 
You may of course also just edit anything yourself if that is preferred.
I hope this is helpful to people!
> Add cookbook chapter on how to read env vars from foreign shell scripts

- .vuepress/configs/navbar/en.ts
This links the contributor book on the navbar, which seems to have been previously linked but removed, probably because it was long and took up a lot of space. As an alternative, this just calls it "Contrib" instead and puts it between "Commands" and "Cookbook" (the alphabetical order was appealing to me)
> Add "Contrib" link to the navbar

- lang-guide/lang-guide.md
I had been wondering how to add arguments to commands directly without a new instance of the shell, as its not documented anywhere as far as i can tell.
Now that i have figured it out a way to do it, i thought id add it to the doc.
I'm not sure if it should be mentioned that `"-a arg2"` does not work, as they become one argument with space instead of the normal two arguments split by space as one would normally expect. That also means that one does not need to double wrap like `'"long arg"'`.
I guess it could also be mentioned that you can also have static arguments instead of, or in addition, like `^$"command" --static-arg ...$arguments`.
> Document dynamic command arguments

- cookbook/files.md
- override existing `Cargo.toml` file with `-f` flag for `save` in example
- Point out `inc` is available through the `nu_plugin_inc`
> fix(files.md): override Cargo.toml in example

- book/pipelines.md
Added an example for PowerShell users showing that you have to explicitly provide pipeline output sometimes, because it confused me when I was switching to Nushell (https://github.com/nushell/nushell/issues/12074).
> Clarify pipeline arguments/output in book

- .vuepress/config.js
- CONTRIBUTING.md
- book/configuration.md
- Minimal configs vs starting from defaults
- `std path add` to simplify editing the system path
- ~~`set-env` from nu_scripts to simplify editing nested configs~~
- Explained more concretely why `env.nu` vs `config.nu`
- Explained why `upsert` is necessary
- Reworded the editors section and removed parts about old Nu versions
- Brief note about `config.nu` not loading non-interactively
- Simplify `nuopen` command to alias
- Reformatted `$env.PATH` snippet more conventionally
- Changed 2 heading levels to improve TOC
- Extra links in general
> Document minimal config files

- contributor-book/plugin_protocol_reference.md
- contributor-book/plugins.md
See https://github.com/nushell/nushell/pull/12309
> Fix plugin reference to `Value::Custom` rename

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/image-actions.yml
- .github/workflows/typos.yml
Bumps the versions of actions used in workflows. This is because the old actions versions use `node` 16 which is at end of life, and support will [soon be deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) on Github. The relevant warnings can be seen, for example, [here](https://github.com/nushell/nushell.github.io/actions/runs/8493326000). As such, the `node` version was also bumped to 20.
> Update workflow actions

- book/testing.md
The testing example used `assert skip`, which no longer exists.
Changed to `#[ignore]`
I believe some other stuff also got caught by the hook, oops
> Fix testing example

- .github/workflows/ci.yml
- .github/workflows/command-block.yml
- .github/workflows/deploy.yml
- .github/workflows/image-actions.yml
- .github/workflows/typos.yml
Upgrade all actions for github workflows
> Upgrade all actions for github workflows

- contributor-book/plugin_protocol_reference.md
This is one of the really important Rust types that wasn't documented in full in the plugin protocol reference, and multiple non-Rust plugin developers said they couldn't quite grasp what was required from the Rust docs, so this provides examples for all of the variants we currently have.
Unfortunately this will need to be kept in sync manually.
> Document all variants of `Value` and fix error types

- book/operators.md
I tried to find its position experimentally (with the help of GPT-4), and it suggested the next test. So I placed the `not` before `and`.
```nu
> not true and false
false
> not (true and false)
true
```
I would be glad if anybody could check my conclusions.
> The `not` operator was missing in the list of the order of operations.

- lang-guide/lang-guide.md
Spelling issues in lang-guide/lang-guide.md +252.
IEE-754 should be IEEE-754
> fix(lang-guide): IEE-754 -> IEEE-754

- commands/docs/dexit.md
- commands/docs/enter.md
- commands/docs/g.md
- commands/docs/n.md
- commands/docs/p.md
- commands/docs/shells.md
Create an entry for `dexit`, which was missing, and add backlinks to the category page to the rest of the commands as well. (Closes https://github.com/nushell/nushell/issues/12642.)
> Update docs for commands from `nu-std/std/dirs.nu`

- blog/2024-04-30-nushell_0_93_0.md
> Release notes for @devyn for 0.93.0

- contributor-book/plugins.md
Just an acknowledgement that plugin tests can now use the lang commands, mostly keywords
Ref: nushell/nushell#12434
> Documentation for nushell/nushell#12434

- contributor-book/plugin_protocol_reference.md
Docs for https://github.com/nushell/nushell/pull/12439
> Documentation for `GetSpanContents` engine call

- book/environment.md
[Related change](https://github.com/nushell/nushell/pull/12701).
> Explain that $env is case-insensitive

- blog/2024-04-30-nushell_0_93_0.md
- book/plugins.md
At least one user on Discord found this surprising, as the `use` command for modules generally does need to be in the config file. Be more clear that it isn't.
> Make clear that `plugin use` is not needed in the config file

- blog/2024-04-30-nushell_0_93_0.md
Some users are confused that Nushell installed again to their user profile, because we never mentioned it (as we changed it during release). Clear this up.
> Warn about Windows Installer on the 0.93.0 release notes

- lang-guide/lang-guide.md
[Lang Ref Guide > Basic Types > Any > Example 1](https://www.nushell.sh/lang-guide/lang-guide.html#example-1)
The result in the example is `'true'` but the right value is `'false'`
> fix: wrong result in an example from 'lang-guide'

- book/nushell_map.md
`InNullOrEmpty` -> `IsNullOrEmpty`
> Fix typo in C#/PowerShell examples

- book/operators.md
There was a mistake with the order of the `not` operator. It has been fixed, and information about the command `help operators | sort-by precedence -r` has been added.
P.S. I'm not a native English speaker. Even though I have consulted with ChatGPT several times, any corrections from native English speakers are welcome!
> Corrections to `Operators precedence` chapter

- cookbook/ssh_agent.md
Currently, the Keychain instructions in the cookbook don't work if you're trying to use GPG and SSH. The instructions assumes you're only using SSH.
With this change, it now removes the empty lines and uses the remaining ones, instead of only using the first 2.
Imo, ideally the page should also mention GPG. But my knowledge is superficial in this matter so I'll leave it to others.
> Fix Keychain instructions in ssh_agent.md

- .vuepress/config.js
Currently, on [nushell.sh](https://nushell.sh), using the dropdown menu and clicking ru-RU redirects you to [nushell.sh/ru.html](https://nushell.sh/ru.html) which results in a 404 page.
This PR updates the configuration file, by appending the path value for the Russian locale `/ru/`.
This also fixes the text displayed on the dropdown as well. 
Hope this helps 😄
> Fix ru link in configuration file

- zh-CN/README.md
> [fix]: fix syntax error in zh-CN/README.md #1395

- cookbook/tables.md
Part of https://github.com/nushell/nushell.github.io/issues/1365
> fix: use correct link to point to the command reduce

- blog/2024-05-28-nushell_0_94_0.md
by opening PRs against the `release-notes-0.94.0` branch.
> Release notes for `0.94.0`

- contributor-book/plugin_protocol_reference.md
- Add `span` to `ListStream`
- Replace `ExternalStream` with `ByteStream`
- Remove `LazyRecord`
- Fix error example, and remove `ShellError` since it's no longer relevant
- Fix some broken links, and update versions
> Plugin protocol reference updates for 0.94.0

- book/dataframes.md
> Dataframes chapter update to reflect the latest changes

- book/configuration.md
There is also `/lang-guide/chapters/types/basic_types/cellpath.html#cellpath`, but given that we are within `/book/` linking to that chapter seems more appropriate than linking to the language reference.
Partial #1365
> Fix configuration cell-path link reference

- i18n.nu
`i18n.nu` is used to update #261
> Improve translation overview text of/for #261

- book/testing.md
`std testing` has been _deprecated_ -hidden to the users to be more precise- for quite some time now...
this PR updates the _testing_ documentation page to not nudge people to have a look at that hiddent module, especially because downloading `testing.nu` manually and putting it anywhere is not a very good workflow :confused: 
i removed all mentions to `testing.nu` and wrote a new section to run tests, which is split into two parts
- running tests from a Nupm package
- running tests for standalon modules or scripts
> update testing doc

- blog/2024-05-28-nushell_0_94_0.md
- book/pipelines.md
This pull request addresses an issue with a broken link that was incorrectly pointing to localhost. The link has been updated to point to the correct relative URL within the documentation.
> fix: Fixed broken link pointing to localhost

- book/installation.md
- snippets/installation/install_pkg_config_libssl_dev.sh
A C toolchain is required to build a number of Rust crates. At least on WSL I ran into an error complaining about a "missin cc linker".
> Add C toolchain to Ubuntu install instructions

- book/thinking_in_nu.md
- book/variables.md
- lang-guide/chapters/filters/00_filters_overview.md
I noticed that the "Thinking in Nu" chapter still had a section discussing the fact that *"Variables are immutable"* even though we've had `mut` for some time now.
There's still some useful information in here, as the *default* should be to use immutables, but it's no longer a *"Common surprise"* that we don't have mutables.
I've reworded and moved this content to the *"Variables"* chapter in the Book.  I've also consolidated some other info I wrote up in the Language Ref that better fits here.
> Link from 'TiN -> Immutable Variables' to Variables chapter to reduce redundancy

- .vuepress/configs/sidebar/en.ts
- book/thinking_in_nu.md
- book/variables.md
- cookbook/input_listen_keys.md
- lang-guide/chapters/filters/00_filters_overview.md
It took me a while to work through the various scenarios for handling `input listen` in a loop, so I figured I'd share the results.
> Cookbook - New section on handling keypress loops using `input listen`

- make_docs.nu
> Document query is a plugin. 

- cookbook/setup.md
The `env` command was removed in 0.77 (https://www.nushell.sh/blog/2023-03-14-nushell_0_77.html#breaking-changes).
Fixes #1289
> Remove mentions of the `env` command

- blog/2024-06-25-nushell_0_95_0.md
- `run-external` changes
- Plugin version reporting
- @cptpiepmatz' new derive macro added to plugin API section, since that's a big target of it
> Release notes for 0.95.0 devyn

- book/installation.md
- snippets/installation/cargo_install_nu.sh
- snippets/installation/cargo_install_nu_more_features.sh
Hi,
This is only a small change.
I have removed the paragraph about including the `dataframes` feature, as it no longer exists (I presume it's just enabled by default?). At least the command `cargo install nu --locked --features=dataframe` given in the book fails with:
```
error: failed to compile `nu v0.95.0`, intermediate artifacts can be found at `/tmp/cargo-install0x8JXF`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
none of the selected packages contains these features: dataframe
```
I also added `--locked` to the remaining `cargo install` command.
> Update installation instructions with `cargo`

- book/dataframes.md
I removed the obsolete warning and added a conventional `Output:` line before the results of block executions (so `numd` can update them out of the box now).
Also, I tested examples with `polars 0.95.1` and they worked with no problems, but I didn't update timings in the markdown as they were without significant changes.
> Dataframes chapter update

- blog/2024-07-23-nushell_0_96_0.md
As instructed in #1457, this is a suggestion for the release notes related to <https://github.com/nushell/nushell/pull/13258>, a breaking change for `std path add`.
To retain the univocality these blog posts seem to have, I offer full editorial control for things like structure, style, grammar, list ordering, etc.
> Document std path add breaking change

- book/configuration.md
I lost several hours to this typo tonight and I don't want anyone else to.
> Fix broken `$env.PATH` example

- cookbook/tables.md
- typos.toml
Following from https://github.com/nushell/nushell/pull/13377 which deprecates the `group` command in favor of a new `chunks` command.
> Replace `group` with `chunks` in docs

- contributor-book/plugins.md
The example given in `contributor_book/plugins` was out of date. `value_string()` was renamed to `type_name()` quite a while ago to reflect what it is actually used for, and `as_mut_any()` was added to support mutating the custom value without having to clone it first.
> Update `CustomValue` usage example

- book/working_with_strings.md
Changes:
* First and foremost, documents raw strings
* Overview table now provides links to the sections themselves with more detail
* Drastically reworked backtick-quoted string section, as the existing doc related these to single-quoted strings. In actually, these are bare-word strings that allow spaces.
* Miscellaneous grammar and phrasing improvements.
I'll come back and revisit the bare-word string section (and more) later, but I do need to get this committed so that I can reference raw strings in a separate PR ;-)
> Substantial improvements to String doc

- book/moving_around.md
Continuing the general clean-up of this chapter that I started when adding the "multi-dot" info.
* General grammar and wording tweaks - In general, tried to remove prepositions, especially "we" (but not all), and focus more on what *Nushell* does. This involves the use of more passive voice, but I hope it reads more professionally in most cases.
* Linked to other sections to reduce redundancy
* Removed the wording about Nushell passing globs "as is" to commands, since this only applies to internals, not externals.  Also it was quite out-of-date, since all applicable filesystem commands now accept `...rest`
* Added raw strings as a valid glob-escaping method
* Clarified the explanation/example of why backticks don't escape globs
* Likewise, the "string to glob" conversion was outdated due …
> More improvements to 'Moving around' chapter

- .vuepress/styles/index.scss
The index.scss style sheet override the line height for codeblocks to 1 but it does not do the same for the line numbers at the left gutter. This commit fixes this.
> Fix line numbers having different line height in code blocks

- de/book/installation.md
- ja/book/installation.md
- zh-CN/book/installation.md
Vuepress was giving several warnings on startup of the dev server related to a missing snippet:
```
/snippets/installation/cargo_install_nu_more_features.sh
```
Running the translations through ChatGPT, this was in the (removed from the English version) section on the `--features` flag which isn't needed currently.  I've removed the relevant sections on building with `--features=all` and `--features=dataframe`.
> Wenn mehr Funktionalitäten installiert werden sollen, kann der folgende Befehl verwendet werden:
That is:
> If you want to install more functionalities, you can use the following command:
Removed the offending sections from German, Japanese, and Chinese translations.
The guides are probably desperately out of date in other areas, of course, and probably need some automated …
> Remove dead snippets from translated Installation chapters

- book/coming_from_bash.md
Implemented suggestion in #1072:
* Added `!!`, `!$`, `!<n>`, and `!<-n>` history substitutions
* Also added a few Bashism keybindings and pointed to the Reedline chapter for the rest.
> History and keybindings in Coming from Bash

- CONTRIBUTING.md
There's more to do here, but this fixes some issues with the existing `CONTRIBUTING.md` for this doc repo.
Fixes:
* Outdated paths for docs (no longer `nu-docs`)
* Outdated path for translation tools (now `tools/...`)
* Also organizes the setup into one-time and each-commit sections
* And formats the translations better
> Updates and fixes for CONTRIBUTING

- book/pipelines.md
Fixes #750  by removing the `inc` command from the example and replacing it with the built-in `update`.
But #750 also surfaced two other issues that need to be fixed:
* We don't provide any list of the "default" plugins that users can install
* The [Commands Help](https://www.nushell.sh/commands) includes commands from these plugins without differentiating them as requiring a plugin.
I'll open issues for these, but I think #750 can be closed with this
> Replace `inc` in pipelines example

- blog/2024-08-20-nushell_0_97_0.md
Slight correction on my PR 13541 - Integers passed to `into datetime` *without* a format string have always been interpreted as nanoseconds.  With this change, they are able to be interpreted based on the format string as well.
> Fix 13541 description

- make_docs.nu
* Uses `$nu.current-exe` to determine the path of plugins rather than `which nu` - This fixes #1516 to allow users with Nu install by `cargo install` to still use `make_docs` with a different `nu`
* Moves plugin retrieval logic to a new function since it's now used in two places
* Slight refactor on plugin retrieval to use `each` rather than a mut-with-for
* Adds an *optional* helper command that will run `make_docs` in a new, temporary subshell with all core plugins installed, even if the user doesn't have them installed already. This implements/fixes #1517.
```nu
source make_docs.nu
make_docs
make docs <path_to_nu>
```
> make-docs: Run in different Nu with plugins

- book/cheat_sheet.md
- book/working_with_lists.md
- de/book/working_with_lists.md
I missed several instances in the previous PR
> Replace `it` with `elt` / `row` / `line` - batch 2

- .vuepress/configs/sidebar/en.ts
- book/README.md
- book/getting_started.md
Related to #1508 - This is in preparation for changing the Navbar so that we can link directly to "Install" and "Getting Started".  It just makes *"Installation"* it's own top-level chapter instead of being a sub-section of *"Getting Started"*.
> Promotes Installation to its own top-level Book chapter

- book/3rdpartyprompts.md
- book/advanced.md
- book/background_task.md
- book/cheat_sheet.md
- book/command_signature.md
- book/creating_errors.md
- book/custom_commands.md
- book/custom_completions.md
- book/default_shell.md
- book/escaping.md
- book/line_editor.md
- book/loading_data.md
- book/moving_around.md
- book/nushell_map_functional.md
- book/nushell_map_imperative.md
- book/regular_expressions.md
- book/shells_in_shells.md
- book/style_guide.md
- book/working_with_lists.md
- book/working_with_strings.md
- book/working_with_tables.md
I used  ¨Chicago Manual of Style" in https://headlinecapitalization.com/
> fix: use consistent headline capitalization

- book/types_of_data.md
I corrected the table content because the binary data type's content was mistakenly replaced with the range data type's content.
The table content is pulled from `/lang-guide/chapters/types/basic_types/binary.md`.
> Fix binary data type table content

- book/configuration.md
Closes https://github.com/nushell/nushell.github.io/issues/1526. This PR documents how to set `XDG_CONFIG_HOME` before starting Nushell.
I don't actually know how to do this if someone has Nushell set as their login shell on MacOS, so if anyone knows how to do that, that'd be helpful.
> Add info on setting XDG_CONFIG_HOME

- lang-guide/chapters/types/basic_types/float.md
I've noticed a broken link in the float type page, so corrected it.
> Fix link parentheses in Float type page

- lang-guide/chapters/types/basic_types/nothing.md
I fixed wrong nothing type literal: `none` → `null`
This page says nothing type literal syntax is `null`.
https://www.nushell.sh/book/types_of_data.html#nothing-null
> Fix nothing type literal: none → null

- blog/2024-06-25-nushell_0_95_0.md
- blog/2024-07-23-nushell_0_96_0.md
- blog/2024-08-20-nushell_0_97_1.md
The breaking changes were split up at some point in two sections but the internal link wasn't updated. This is now pointing at the full list of breaking changes again.
> Fixes broken links

- .vuepress/configs/navbar/en.ts
Floating an idea ...
*"Ref"* is just too short and ambiguous to describe the *"Language Reference Guide"* on the main page navbar.
What about grouping the *"Documentation"* together into its own dropdown?  This allows us to provide a full and descriptive name for each doc link.
> Dropdown for doc on main page

- book/dataframes.md
- book/plugins.md
* Also updates DataFrames chapter to remove erroneous installation information. Points back to Plugins chapter for installation.
* Moves the "implementation" paragraph from the top down to the developer section
* Adds a callout on version matching near the top
* Trying out the automatic `[[toc]]` here (and in DataFrames). This populates a table-of-contents with links to each heading. We can easily (and IMHO should) add this to more chapters in the documentation.
* Adds a section listing the Core plugins that ship with Nushell and how to use them (addresses #1514).
* Changes code blocks to remove `>` prompt to match style guide.
* Reworks heading titles and levels for consistency and flow
* Other miscellaneous improvements
> Plugin Chapter update

- lang-guide/chapters/types/basic_types/record.md
- lang-guide/chapters/types/basic_types/table.md
Based on a question in Discord today, I realized that `wrap` (while incredibly useful) isn't well promoted.
I'll also look at adding some help keywords to `wrap`, but at the least, it should be listed as a way to cast to `table` and `record`.
> Add `wrap` as a cast for table and record

- book/standard_library.md
* Adds some much-needed detail to the `std` doc
* Removes the link to the Nushell GitHub repo - The `README` there is out of date anyway, and the doc should be rendered by the SSG (VuePress) rather than in a GitHub Markdown file whenever possible.
* Might be controversial, but I note the performance issues that prevent new commands from being added to `std` at the moment.  I think it's a good explanation give the current state, and it doesn't come across too harsh, hopefully.  I can remove it if needed.
> `std` doc page

- blog/2024-09-17-nushell_0_98_0.md
by opening PRs against the `release-notes-0.98.0` branch.
> Release notes for `0.98.0`

- .vuepress/configs/sidebar/en.ts
- lang-guide/chapters/mime_types.md
In the [meeting of the 18.09.2024](https://hackmd.io/@nucore/H1bgUtLaC) we talked about adding recommended MIME types for Nushell to the documentation. This is the PR for that.
I added it to the `Language Reference Guide` as this part seems to more about the internals and not so much about using Nushell, so I though it would fit there. If not, let's change that.
> Documented the recommended MIME type for Nushell

- cookbook/http.md
You can't use implicit `$it` with `each` in current versions of nushell any more.
> Remove outdated mention of $it

- book/coming_from_bash.md
I think knowing `explore` and `first` are extremely helpful for *nix users that are used to using `less` and `head`, so I think they should be included in the [Coming from Bash](book/coming_from_bash.md) page. I also think there should be more clarification about which things are useful for external versus internal commands.
> `coming_from_bash.md`: add references to `explore` and `first`

- README.md
- de/README.md
- es/README.md
- ja/README.md
- pt-BR/README.md
- ru/README.md
- zh-CN/README.md
This PR unifies the language identifiers of the code blocks for installation commands to 'sh'.
Syntax highlighting will be applied to the modified code blocks, and the extra $ sign at the beginning will be removed when copied.
> Unify the language identifiers of the code blocks to 'sh'

- book/installation.md
- book/plugins.md
Just a quick update:
* Update installation chapter to note that plugins need to be installed separately with Cargo
* Add a one-liner in the Plugins chapter to install all the default plugins at once
> One-liner for installing plugins with Cargo

- book/modules.md
- book/scripts.md
Highlights some differences between how scripts and modules handle `main`, and explains in further detail how and why `def main [] {}` is required for subcommands to be visible
> Highlight the differences between scripts and modules

- book/programming_in_nu.md
The "Input-Output Signature" chapter was moved into "Custom Commands", which resulted in a broken-link-warning. Since this is no longer a top-level chapter, I removed it from the "Overview" page.  Also fixed a minor typo (I think it was mine in the first place) while I was there.
> Fix broken link from Custom Commands update

- book/hooks.md
This PR adds an additional example for Windows to the existing command_not_found hook documentation.
For example, I used this to find the program path of excel after typing `excel` resulted in `command_not_found`
> add Windows command_not_found example

- .vuepress/config.js
While I would certainly love to turn line-numbers off (or at least only use them when there's a certain number of lines in the code-block), as mentioned in #1573 this just doesn't seem to work in Vuepress at the moment when using Shiki.  Attempting to turn them off makes the problem *worse* by only removing the line-number from the last line, while keeping the rest:
This PR turns them back on to at least fix that bug.  I don't yet know what the long-term solution should be.
It seems odd to me that this is broken at the Vuepress/Shiki upstream, but as mentioned in #1573, I reproduced it in a clean environment.
> Turn back on line-numbers

- blog/2024-10-15-nushell_0_99_0.md
Adds breaking change information regarding `std` to 0.99.0 release notes
> std-lib breaking changes

- blog/2024-10-15-nushell_0_99_0.md
This PR includes details about Unicode code points in keybindings, as requested in [the comment](https://github.com/nushell/nushell/pull/14020#issuecomment-2399909753). The changes are based on the improvements introduced in [#14020](https://github.com/nushell/nushell/pull/14020).
> Added changes to release notes for version 0.99.0 due to nushell/#14020

- book/standard_library.md
Updates for the Standard Library changes that will be a part of the 0.99 release.
> Standard Library updates for 0.99

- lang-guide/chapters/types/type_signatures.md
Closes https://github.com/nushell/nushell.github.io/issues/1595
Cc @NotTheDr01ds
> Remove unsupported syntax from type signatures

- lang-guide/chapters/types/type_signatures.md
After #1596, the examples for type signatures on custom commands were removed entirely, even though the text above said they were still included.
This adds type signature examples back in, but correctly this time.
> Fix type signatures on custom commands

- book/scripts.md
The example was not running correctly, without `main []`
It resulted in the following error:
```
1 │ ╭─▶ #!/usr/bin/env -S nu --stdin
2 │ │   
3 │ │   echo $"stdin: ($in)"
4 │ │     
5 │ ├─▶ 
· ╰──── block is missing compiled representation
```
> wrapped script in "def main [] {...}"

- book/testing.md
I couldn't use `nupm` as it was marked as experimental so I thought I'd see how far I could take the "reflection" capabilities of Nushell for basic unit testing. I imagine we could create a somewhat full-featured test framework using something like this technique. I'm somewhat tempted to try 😄.
I can simplify the example by removing the ignored tests and printing of test names if you prefer, but it seemed useful enough to leave in.
> Example showing discovery and running of test commands

- book/working_with_tables.md
Implements #1574 
Also, while there, I noticed that the chapter on Tables doesn't have any info on the `table` command, which seemed a bit odd - Added some detail regarding it, since it sometimes causes confusion.
> Updates to "Working with Tables" - Adds info on "index renaming" and the table command

- book/custom_commands.md
- book/style_guide.md
As per Discord, raised to help document the commonly used naming and make it easier for newbies to see normal usage and help staying consistent with standard library usage. Hopefully all standard practice and nothing controversial here. The foundations were taken from [this comment in Discord](https://discord.com/channels/601130461678272522/615329862395101194/941324199748853760)
This does feel a little verbose but I couldn't think of reducing it without removing the examples.
There was also a question about restructuring this page. Not sure I'm best placed to do that, but happy to give that a shot with more guidance.
> Added candidate naming convention to the style guide

- book/modules/creating_modules.md
> Fix 'Creating Modules' code examples

- book/modules/creating_modules.md
cc @Kissaki 
Related #1609 and #1610 
Hopefully this change (finally) gets us consistent results on all systems, since it now uses `$nu.default-config-dir`.
@Kissaki Thank you for finding and attempting to fix the issue!  Clearly neither of our previous fixes works for the other (and that's still bugging me, so I may ping you on it again if I have ideas).
> Change "local environment" example (yet again!)

- book/coming_from_cmd.md
Replaces #1605 (which documented behavior across versions).
The "if no executable by that name exists" has been wrong since 0.94.0 (not disclosed in release notes, but consequence of 6c649809d38a687cd63b59ab028b7f30207e5663 [PR 12921](12921)).
The "used to" (prior version 0.67 2022-08-16) is very old, and no longer worth it to keep.
Add information about forwarded commands overshadowing external files.
> Update forwarded cmd.exe commands docs

- book/installation.md
Documentation on how to use the recently added Docker images in nushell/nushell#14171.
> Docker image usage

- book/modules/creating_modules.md
- book/modules/using_modules.md
- book/standard_library.md
Addresses #1597 feedback from @132ikl.
> Module Chapter Edits from Review

- .vuepress/config.js
Fixes #1573 on my local system (as well as my test VuePress repo).  Had to look at the VuePress Ecosystem doc repo to see what they were doing.  Turns out we need both PrismJS line-numbering config in addition to Shiki config.
I've set both to start numbering code-blocks when they have 10 or more lines.  This seems to work fairly well.
> Fix code-block line numbering

- README.md
- book/configuration.md
- zh-CN/book/configuration.md
This is a companion doc PR for nushell/nushell#14275
> Update `VISUAL`/`EDITOR` order

- book/custom_commands.md
Misleading type since $name is not a parameter
> Typo in example provided in custom_commands.md

- blog/2024-11-12-nushell_0_100_0.md
by opening PRs against the `release-notes-0.100.0` branch.
> Release notes for `0.100.0`

- book/modules/creating_modules.md
- book/standard_library.md
Importing `std/log` into another module requires some special-care due to its environment variables. Previously, this caveat was discussed as a more general use-case, but `std/log` is so common that it should be explicitly documented.
> Be more specific about std/log use in modules

- cookbook/direnv.md
This PR updates the nushell cookbook's direnv integration recommendation so that `$env.PATH` will be stored as a nushell list rather than as a colon-separated string.
Before this change, my `$env.PATH` looks like this:
```
> $env.PATH
/Users/jasha/bin:/Users/jasha/.cargo/bin:/Users/jasha/.local/bin:/Users/jasha/.nvm/versions/node/v18.19.0/bin:/Users/jasha/.pyenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/iTerm.app/Contents/Resources/utilities
```
After the change, `$env.PATH looks …
> Update direnv.md - use ENV_CONVERSIONS

- book/coming_from_cmd.md
Add if defined expression via `scope variables`
> Add missing cmd to nu command

- book/coming_from_cmd.md
The CMD.EXE `START` command does way more than open the file explorer on a directory path. That is only the case when passing a directory path as a parameter.
* Split START reference into three cases:
1. Open path in default app
2. Execute internal command
3. Execute batch file
* Add documentation about Nushell's own `start` command, which overlaps with CMD.exe START
Although Nushell `start` can be used to execute bat files, doing so does not open a new console window like CMD.EXE START does. Hence, no such mapping is added.
> Fix and extend CMD.EXE START docs

- book/pipelines.md
Replace "Notes on Errors when Piping Commands" section content with PowerShell references with neutral and more general and extensive "Command Input and Output Types" content.
* Approach the input output types docs from the Basics context rather than PowerShell behavior and situational errors
* Introduce in a more natural and introductory order:
1. Discover input output types of commands via `help`
2. Usable case
3. Problematic case with unintended behavior due to command default behavior
4. Unsupported case with error
* Add example pipeline expressions for the supported good case
* Describe alternatives like before
* Keep description of why and in what way commands differ in input output support
With the new approach, mentioning PowerShell felt misplaced. Nushell stands well on its own. …
> Improve pipelines input output types documentation

- book/modules/using_modules.md
The relative example follows afterwards. This block only contains docs on absolute paths.
Split from #1608 so the fix can be merged without further discussion. The other splittable fixup 9eea190c86573d0354ae169bdb9b82bc436f7bb4 has apparently been resolved through another PR #1620.
> Fix absolute path example item text

- book/escaping.md
The history note (historic behavior, in the past) is very old. It has little value in the current docs.
The "shell built-ins" wording and description may not be obvious to readers.
The Coming from CMD.EXE documents the internal command forwarding as well as other relations between the two shells. Here, in 'Escaping the System', we should focus on the aspect of escaping to the system, only give a general description and note, and reference to the more definitive and exhaustive documentation.
> Update and simplify Escaping to the System Windows Note

- book/installation.md
- book/plugins.md
- contributor-book/plugins.md
- es/book/instalacion.md
- pt-BR/README.md
- pt-BR/book/instalacao.md
- snippets/installation/build_nu_yourself.sh
- snippets/installation/cargo_install_nu.sh
Using the `--locked` flag prevents installation failures when dependencies have broken updates.
All references are replaced. Closes #1641.
An accompanying PR will be opened for nushell/nushell.
> Add `--locked` flag to Cargo install

- contributor-book/plugins.md
This PR fixes a typo in the python plugin example (occurs twice) that prevents the code from working if a reader tries to run the code as given.
> plugins.md - fix typo in python example code

- cookbook/external_completers.md
- nushell/nushell#14398
- nushell/nushell#14399
We no longer need to prepend the header row to make sure about the number of columns.
Updated the fish completer to a more clean & performant version.
Also updated the descriptions below accordingly.
> Update the Fish completer to leverage nushell/nushell#14399

- book/explore.md
- commands/docs/explore.md
some of the keybindings added to the documentation are existing (i.e. the `Vim` keybindings), and some of them will be added via https://github.com/nushell/nushell/pull/14468 (i.e. the `Emacs` keybindings)
> `explore`: cleanup params/flags and add more keybindings

- cookbook/polars_v_pandas_v_nushell.md
This PR just updates the dataframe cookbook using the polars plugin.
> update the dataframe cookbook walkthrough

- book/default_shell.md
At @132ikl's recommendation in the #1656 review, added a link from the "Default Shell" section in the Installation back to the Configuration chapter.  In the upcoming update to the chapter, this will also have a link in the other direction as well, but these can be handled separately.
> Added backlink from "Default Shell" to Config chapter

- book/configuration_preview.md
As I was closing #1527, I realized that I hadn't noted that `XDG_DATA_DIRS` are only used for autoloads on Unix/Linux.  This is a minor update to call that out.
> XDG_DATA_DIRS are Unix-only

- book/quick_tour.md
Overall, this keeps the structure of the Quick Start, with some changes:
* Overall, I think it's more "newbie friendly", with more callouts, tips, links, etc.
* Does away with snippets, as with other updates.  All code-blocks are embedded in the page.
* Adds Headings to make it easier to see when we jump between topics, which also ...
* Adds a Table of Contents
* Updates all examples to use `# => ` on output.  This allows the *Copy* button to be used on the code-block without attempt to "run a table" ;-)
* Wordsmithing to try to make key concepts a bit more clear.
* (Major) Reduces the emphasis on nested data, as that's a bit more than "Quick Start" material.  I still mention nested data, with a link to the relevant section of the doc for more detail.
* (Major) Adds a *brief* section on …
> Quick Tour chapter update

- book/moving_around.md
Fixes #1664 and, while I was making changes in "Moving Around the System":
* Changed code snippets to be embedded code blocks as in other chapters
* Updated all examples to use the "standard" code-block style
* Added a section on `mkdir` since the `-p` thing seems to be a common point of confusion.
> Moving Around Fixes and Updates

- book/custom_commands.md
A good number of people seem to get caught up on needing to use `def --env` for custom commands with `cd`. There is already a note in the help page for `cd` about this, but it would help if the dedicated section on this topic came up with you searched `cd` also. It seems most people don't think to type "changing directories" causing them to miss this section. This is a bit of a hack, ideally we would change something in the Docsearch/Algolia config to add some sort of an "alias" but I'm not sure if that's possible so this should be a sufficient workaround for now.
> Add `cd` to title of Changing Directories in a Custom Command section for searchability

- lang-guide/chapters/types/basic_types/list.md
'get' was listed twice as a command that can be used with lists
> Removed duplicate 'get' in list.md

- book/creating_errors.md
Use `$span` variable in `my-command` function definition from code example.
> Update creating_errors.md to use $span variable directly in example

- book/how_nushell_code_gets_run.md
- book/thinking_in_nu.md
Another fairly substantial update to the "Thinking in Nu" chapter.  It adds two major topics that often confuse new users:
* Implicit return
* Only the last value of an expression is returned
Also:
* Major update to *"Think of Nushell as a Compiled Language"* and the linked *"How Nushell Code Gets Run"* chapter
* There was a lot of duplication between the two chapters.  The code-examples that fail parsing in Nushell have now been moved almost exclusively the to the *"Thinking in Nu"* Chapter and out of *"How Nushell Code Gets Run"*.  There are links between the two chapters where needed.
* This is hopefully much more clear.  I certainly understand it better ;-)
* Previously, the *pain point* of lacking an `eval` was much more visible than the benefits.  Hopefully the benefits are more …
> Add "return value" topics to "Thinking in Nu"

- book/pipelines.md
Before: 
```
/tmp/nushell_experiments> do { $env.config.table.mode = none; ls }
Error:
× External command calls must be explicit in assignments
╭─[entry #37:1:31]
1 │ do { $env.config.table.mode = none; ls }
·                               ──┬─
·                                 ╰── add a caret (^) before the command name if you intended to run and capture its output
╰────
help: the parsing of assignments was changed in 0.97.0, and this would have previously been treated as a string. Alternatively, quote the string with single or double quotes to avoid it
being interpreted as a command name. This restriction may be removed in a future release.
``` 
After: 
```
/tmp/nushell_experiments> do { $env.config.table.mode = "none"; ls | table }
0   2024-12-19 Report   dir    4.0 KiB   28 minutes …
```
> Fixed some examples for Command Output in Nushell

- book/stdout_stderr_exit_codes.md
The "which" in the original sentence sounds like it is referring to the raw bytes.
> internal nushell commands use structured data

- blog/2024-12-24-nushell_0_101_0.md
Added release notes related to my changes-to-date.
Anything not listed falls into the "other fixes" category that doesn't require additional detail.
> Release notes for NotTheDr01ds PRs

- book/configuration.md
- book/externs.md
- book/nu_as_a_shell.md
- book/pipelines.md
- book/working_with_strings.md
- lang-guide/chapters/types/basic_types/range.md
Just fixing some minor errors I noticed while reading the book!
> Fix minor errors in book

- blog/2024-12-24-nushell_0_101_0.md
> Additions from full-changelog for NotTheDr01ds and WindSoilder

- blog/2024-12-24-nushell_0_101_0.md
by opening PRs against the `release-notes-0.101.0` branch.
> Release notes for `0.101.0`

- book/line_editor.md
- book/quick_tour.md
- book/thinking_in_nu.md
The primary purpose of this PR is to add information on multi-line editing as mentioned in #1671.
Of course, as often happens, I rabbit-trailed into other fixes and updates along the way:
* Reedline:  Added table-of-contents
* Reedline: Added multi-line editing section
* Reedline: Added a number of missing keybindings to Emacs and Vi modes
* Reedline: Formatting keybindings using `<kbd>` tags
* Reedline: Miscellaneous wordsmithing
* Reedline: Removed section on configuring the Prompt, as this is covered in the Configuration chapter.  Added link.
* Quick Tour: Added link to Multi-line Editing
* Thinking in Nu: Added link to Multi-line Editing
> Multi-line editing and other updates

- .github/workflows/command-block.yml
- commands/docs/ansi.md
Trying to use the `pull_request_target` triggeer instead, as that has
apparently different permissions according to:
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target
> Try to get the command doc comment bot working

- book/configuration.md
Fixes an issue found in #1710 along with removing a few other (now unnecessary) references to `env.nu`.
> Fix `config nu` reference

- .vuepress/config.js
* Disables the PrismJS highlighter entirely (I hope), setting Shiki as the highlighter for both VuePress and the theme.
* CSV was apparently getting parsed through Prism previously, so this also adds the `csv` language to the Shiki config
* And this changes the Shiki code-block theme from `dark-plus` to `vitesse-dark`.  This does not appear to change any `nu`/`nushell` syntax highlighting, but it does enable proper `ansi` coloring.
This might finally explain why line-numbers were being applied by both Shiki and PrismJS previously.
> Disable PrismJS

- .vuepress/config.js
The color choices in the theme added in #1714 don't work well for Nushell codeblocks.  Reverting to the original while we either look for a theme that works well (and supports `ansi`) or add the ANSI CSS styles in manually.
> Revert codeblock theme

- book/custom_commands.md
- book/thinking_in_nu.md
Just a couple of random issues (my mistakes in the first place) found and fixed in the Book.
> A few typo fixes

- .vuepress/config.js
Use the one-dark-pro theme only for `ansi` code blocks. Additionally, override the background color to be the same as `dark-plus`.
I can switch the theme if others would prefer, but I think the `one-dark-pro` theme looks decent along with the other code blocks, and is very readable. Here's an error using `ansi`, highlighted with `one-dark-pro`:
> Apply theme change only for ansi highlights

- .vuepress/config.js
Currently, in light mode, there's no code highlighting:
This is a quick fix so that light mode also uses the dark-plus theme for code blocks.
I think this happened because previously, we just had `theme: 'dark-plus'`, whereas now have a `themes` object where the light theme needs to be specified.
> Use dark-plus in code blocks for light mode also

- blog/2024-06-25-nushell_0_95_0.md
- book/moving_around.md
- book/quick_tour.md
- fr/book/moving_around.md
Just a little PR to fix a broken link (markdown typo) and fix a `CVS/CSV` typo.
> Fix broken link + typo

- es/book/aliases.md
- es/book/cargando_datos.md
- es/book/configuracion.md
- es/book/entorno.md
- es/book/escapando.md
- es/book/instalacion.md
- es/book/matematicas.md
- es/book/metadatos.md
- es/book/pipeline.md
- es/book/trabajando_con_tablas.md
- es/book/variables_y_subexpresiones.md
- fr/book/cheat_sheet.md
- fr/book/thinking_in_nu.md
Split out Spanish and French for #1684. Didn't appear to have any of the same indentation issues but I could be a bit tab-blind after all this, lol.
> Es and fr book

- .vuepress/styles/index.scss
This should make the color of the copy code button in code blocks (including the "Copied" notification) white in light mode, to make it stand out better against the dark background. The button is already white in dark mode.
Fixes https://github.com/nushell/nushell.github.io/issues/1727
> Use white foreground for copy code button

- book/configuration.md
It seems like the `s` at the end is a typo.
> fix typo in configuration.md `($nu.data-dir)/vendor/autoloads`

- make_docs.nu
* Completes #1722 by adding frontmatter to Nushell Commands and Categories pages to remove the *"Edit this page in GitHub"* link.
* Also removes the *"Contributors"* list since it is not accurate for these pages.
* And implements a workaround for https://github.com/vuejs/core/issues/12088 by placing table heading rows inside a `<thead>` and table body rows inside a `<tbody>`.  This shouldn't be necessary, but without it VuePress will now generate ugly warnings for each of the Category pages.
> Remove "Edit this page" and contributors list from Command docs

- book/nushell_map.md
Removes the `split-by` command from the doc.  This is the only non-blog/command-help reference I could find in the English docs.
Also removes the reference to 0.94 in that page.
Also checked for `date to-table` and `date to-record` as they have been deprecated/removed - There wasn't any use of those commands that I could find.
> Remove deprecated/removed split-by command from Map table

- contributor-book/plugin_protocol_reference.md
- contributor-book/plugins.md
Forgot to follow up https://github.com/nushell/nushell/pull/13598 here.
Supersede that part of closed #1724
> Fixup `usage`->`description` in plugin stuff

- book/installation.md
Adds info on how to install the required dependencies to build Nushell on macOS with Nix.
> Add package dependencies for Nix on macOS

- lang-guide/chapters/pipelines.md
It's a copy paste from https://hackmd.io/R-r2khDpRvenRg9GndTAgw#Stdout-File-Redirect-ogt.  Additionally with more examples about custom commands.
I think it's good to add to lang-guide, as a follow up of https://github.com/nushell/nushell/pull/14821
> add pipeline examples

- book/thinking_in_nu.md
The link to the save command wasn't shown correctly,  because the whole markup was wrapped in backticks.
> Show link for save command

- blog/2025-01-30-twin00283.md
* Adds this week's TWiN to the blog
* Given the formatting (bold green for links), having multiple PRs on each line was difficult to read.  For this reason, this TWiN places each PR link in its own bullet.
> This Week in Nushell 283-284

- blog/2024-01-06-twin0228.md
- blog/2024-01-19-twin0230.md
- blog/2024-03-01-twin0236.md
The current main branch state fails CI build typo checks. These were introduced through 66c88881f3a1205679adb8a45a2e61b97183a809 (#1765).
Correct the reported typos.
> Fix blog post typos

- fr/book/README.md
- pt-BR/book/README.md
On translated pages, rather than point to non-existing pages resulting in a 404 not found page being shown to the user, do not link anywhere.
---
Before this change, launching vuepress reports
```
warning Broken links found in fr/book/README.md: dataframes.md
warning Broken links found in pt-BR/book/README.md: shells_em_shells.md
```
The live pages with the dead links:
* https://www.nushell.sh/fr/book/
* https://www.nushell.sh/pt-BR/book/
> Drop invalid links in translated content

- zh-CN/book/moving_around.md
remove an incorrect warning for `cp` command
`cp` always overwrites existing files
> fix: zh-CN/book/moving_around

- book/aliases.md
This PR reimplements the shadowed `ls` alias to use a `do { |closure| }` expression instead of making two custom commands alongside an alias. (Though, it could be rewritten into a custom command with the loss of documentation of the original command.)
I thought the manner the docs achieved an `ls` shadow could be changed because 2 custom commands seemed like a fair bit.
> docs(aliases): refactor the ls shadow alias

- book/coloring_and_theming.md
* Drop ambiguous hash label - works just fine with only the symbol `#`
* Clarify when it is commented out vs may be (hex) value
* Drop text table of contents; the website has it's own sidebar table of contents / headline jump list
* Fix headline levels - the general color declaration docs were under Table Borders, and hex and full hex were not on the same level, and primitives had a sub-headline one level too deep
* Introduce/Rename main section 'Color Configuration'
* Show command to print the current configuration
* Add closure declaration format documentation
* Drop separators following headlines; other headlines do not have this, they make no logical sense, and they lead to double-separator-lines being rendered on the website
Resolves #1503
> Fix and extend color documentation

- book/custom_completions.md
Document the fact that custom/external completers can return `null` to fall back to file completions (implemented in https://github.com/nushell/nushell/pull/14781).
> Document file completion fallback for custom/external completers

- .vuepress/config.js
Partial fix for #1765.
This at least should get the newer Blog articles back at the top of the RSS/Atom feeds, but there are still problems (and could be more):
* Feed date still shows the GitHub commit date
* Might be issues when the post filename does not have a valid date - I haven't had a chance to test yet, but will soon.
> Sort feeds based on filename date first

- book/coloring_and_theming.md
The `config.nu` no longer contains the full configuration, so make the suggested code a oneliner assignment.
Add a commented-out (not rendered Markdown) command to generate the list, which will ease updates in the future.
Update the list of options.
Add an example demonstrating how the border style can change.
> Update table border configuration docs

- blog/2025-02-04-nushell_0_102_0.md
The inline code formatted too much as code. "command" is part of the sentence, not the code/command.
> Fix inline code format fencing

- blog/2025-03-04-nushell_0_103_0.md
As pointed out in https://github.com/nushell/nushell.github.io/issues/1788, the 0.102 release notes don't link to the list of core plugins. I threw in a link to https://www.nushell.sh/book/plugins.html#core-plugins
> Include link to plugins

- book/custom_commands.md
Not quite sure how I missed this when updating the Custom Commands chapter a while back, but as multiple folks have pointed out on Discord, it didn't include any information on `def --wrapped`.  This update includes that info.
> Add `def --wrapped` doc

- ja/README.md
`Nu はでは` in the Japanese README is incorrect Japanese.
Therefore, I amend it to `Nu は`.
> Fix Japanese README typo

- book/coloring_and_theming.md
- de/book/coloring_and_theming.md
- zh-CN/book/coloring_and_theming.md
`build-string` command was apparently removed years ago and somehow survived in the docs until now. Brought to attention in https://github.com/nushell/nushell/issues/15116
> remove mention of `build-string` from coloring_and_theming.md

- blog/2025-02-08-twin0285.md
Fix a bug where I Inadvertently copied the link to the release-notes from the dev-server and put a localhost link into production last week.
> Fix bad localhost link in TWiN 285

- book/custom_commands.md
A random letter `d` that was actually `₫`
> Fix typo in custom_commands

- blog/2025-02-14-twin0286.md
> Twin #0286

- es/book/configuracion.md
Although outdated, it's better to be *more* correct.
*Correct me if I'm missing something here, but I don't see what else the previous code block was meant to show.*
> Fix outdated `config path` code block

- book/configuration.md
- book/operators.md
- book/pipelines.md
- book/testing.md
- contributor-book/plugin_protocol_reference.md
- cookbook/ssh_agent.md
- de/book/custom_commands.md
- de/book/pipeline.md
- lang-guide/chapters/pipelines.md
CONTRIBUTING.md defines a preference of `nu` over `nushell`, which overwhelmingly matches our code blocks.
These 66 occurrences were the outliers.
> Consistently use `nu` as code block lang

- cookbook/setup.md
help: the parsing of assignments was changed in 0.97.0, and this would have previously been treated as a string. 
Alternatively, quote the string with single or double
quotes to avoid it being interpreted as a command name. This restriction may be removed in a future release.
> fix(setup.md): Quote the EDITOR value

- lang-guide/chapters/types/basic_types/range.md
I've corrected a typo in the numbers. (10 → 5)
> Fix a typo in range type explanation

- book/custom_completions.md
I've updated the documentation to clarify how to change the prompt marker for the completion menu, specifically, modified the instructions to reflect that the `marker` value in the `$env.config.menus` list should be changed where the `name` key is `completion_menu`.
> Correct the tip for changing completion prompt marker

- blog/2025-03-18-nushell_0_103_0.md
`find -f` does not exist. It should be `help -f`.
I decided to primarily use `--find` instead of `-f` to make it clear what the command parameter is for.
> Fix 0.103.0 release notes help command reference

- cookbook/external_completers.md
See discussions on https://github.com/nushell/nushell/issues/10690
Demo tested nu 0.103.0
I gave an example by manually checking if the value is path, but this means for super fat completions like docker or git you'll experience lag from the sheer amount of FS calls.
Alternatively, a person could probably do something like 
```nu
| update value { str replace "\"" "\\\"" | $"($in)" }
```
but that's going to fail in edge cases.
> COOKBOOK/EXTERNAL_COMPLETERS.MD Add filepath escape troubleshooting

- book/plugins.md
A few folks in [Discord ran into issues using plugins out-of-the-box](https://discord.com/channels/601130461678272522/1347588123122466980) recently, and correctly noted that the Book currently lacks a *cohesive* overview of how to do this simply.
This update provides a QuickStart near the top of the Plugin Chapter that should get folks started more easily.
Also note [#15380](https://github.com/nushell/nushell/pull/15380) in the main repo which should make this even easier by automatically adding the default binary path.
I'll update this QuickStart again once that it is in place in 0.104.
> Updated Plugin Chapter to add Overview/QuickStart

- book/operators.md
Simply adds a mention of the new operators `has`  and `not-has` in the book.
> Add mention of new operators

- blog/2025-03-18-nushell_0_103_0.md
Adds a note about the missed breaking change, including how to update your zoxide completer.
Related: #1845, #1847
> Add note about breaking completions change to 0.103.0 changelog

- blog/2024-01-09-nushell_0_89_0.md
- blog/2025-03-29-twin0292.md
> Added TWiN 292

- book/coloring_and_theming.md
The instructions for using Nushell with the light theme used defunct variables.
The updated instructions import the values from `config` instead, which works on my machine. 
- I'm new to Nushell; I think my instructions just put the `light-theme` and `dark-theme` variables in scope, but I'm not sure. 
- I have not tested the website since I do not think my changes are just to content and I'm not confident doing the setup.
> Correct light theme instructions to use module

- blog/2025-04-04-twin0293.md
> Added TWiN #293

- .vuepress/configs/sidebar/en.ts
- book/special_variables.md
Added a "Special Variables" page to the "Nu Fundamentals" chapter.  How many did I miss?
> New chapter page collecting the list of special variables

- lang-guide/chapters/pipelines.md
A couple people have made issues about this broken example, so adding a note here that it's broken until nushell/nushell#15326 is fixed
Not sure if this is bad form, but seems better than removing the examples for now and hoping someone remembers to re-add them (cc @NotTheDr01ds)
Rel: https://github.com/nushell/nushell/issues/15561, https://github.com/nushell/nushell/issues/15416
> Add note about issue #15326

- blog/2025-04-18-twin0295.md
> Added TWiN 295

- cookbook/external_completers.md
Invert fish quotes to prevent issues where the output is a single double quote, breaking the string substitution
https://github.com/nushell/nushell.github.io/issues/1881
the TL;DR above is that if you do something like `cat <TAB>` instead of `cat scri<TAB>` the string substitution would break from some funky nushell quoting issues.
cc @ysthakur
> Update external_completers.md - Fix fish quotes for ISS1881

- blog/2024-01-09-nushell_0_89_0.md
- blog/2025-04-15-nushell_0_104_0.md
Tell me if it's alright or if there is something I need to change.
Especially I wasn't sure if/where I should include "breaking change" block
> release notes 0.104.0: datetime handling highlights

- book/hooks.md
- de/book/hooks.md
- zh-CN/book/hooks.md
Fix hooks syntax; they are a list of values. The code as it was did not run.
Nushell has been using an inherent configuration and the user configuration only replacing parts. For the hooks it makes sense to set only the hooks value.
Replace "you can also use a list", which is the default and used above already, with a "you can append additional hooks" example.
For zh-CN, at least add the missing available hook docs in English instead of missing them altogether.
For zh-CN, add the new example replacement with EN text rather than keeping the old outdated one, or missing it altogether.
Resolves #1879
> Fix hooks.md basic hooks examples and hooks list

- book/control_flow.md
> Add try on external commands mention

- blog/2025-04-15-nushell_0_104_0.md
For https://github.com/nushell/nushell/pull/15511
> Notes for 15511 (substring match algorithm)

- blog/2024-06-25-nushell_0_95_0.md
- blog/2024-07-23-nushell_0_96_0.md
0.95.0 mentions `$nu.vendor-autoload-dir` future-facing (will be introduced in the future).
But it was introduced as `$nu.vendor-autoload-dirs` (plural) in 0.96.0.
0.96.0 mentions PRs #13217 and #13382.
The first introduced it in singular, but the second changed it to plural. The plural name `$nu.vendor-autoload-dirs` is still the correct name in the current version 0.103.0.
> Fix release notes `$nu.vendor-autoload-dirs`

- cookbook/modules.md
> Add cookbook virtual env overlay docs

- .vuepress/config.js
Regression introduced in 2ec6143edbf6b9412a2e8a951fb90a91d355bb1a
Missing comma is missing on the first, newly introduced array element, and somehow that does not lead to build errors, but probably to runtime issues.
> Fix vuepress config

- .vuepress/styles/index.scss
Code blocks use a different variable, which this commit adds.
On the current Nushell website, for example [Quick Tour][quicktour] page, we can see that the font-family being applied is in the generated style-*.css, with declaration `code { font-family(--code-font-family); }`, which does not match our supposed override which defines a var under a different name `--font-family-code`.
This var name has been used since the introduction of the override in 83ced1debcfe2cffb6b7aad597de92134c3f4e64.
Maybe vuepress changed the variable at some point?
This is a follow-up to 2ec6143edbf6b9412a2e8a951fb90a91d355bb1a (PR #1890, PR #1906), which attempts to solve Android monospace due to missing font coverage (#83).
Instead of replacing `--font-family-code`, `--code-font-family` is added as an …
> Add missing code font var

- contributor-book/plugins.md
Please verify as I am not very familiar with Rust.
Tested working with a `seq` stream, a string, and a list of values as I would expect from the implementation.
Tested `help len` and unexpected type in as well.
Content that follows on the page has not been tested or adjusted.
Resolves #1734 and #1066
> Fix plugins streaming sample

- contributor-book/plugins.md
Plugins compiled with v0.103.0 do not run in Nushell v0.104.0.
This sample has been compiled in v0.104.0 and runs and behaves like expected.
> Update Plugins with v0.104.0 dependencies

- .vuepress/styles/index.scss
VuePress puts our `:root` declaration before their own, meaning the declaration we intended as an override was overridden instead.
Use higher specificity (`body`) to make sure it takes precedence.
This is a follow-up to #1907
> Fix code font family declaration

- contributor-book/plugins.md
> Fix Plugins infinite int stream sample

- lang-guide/chapters/pipelines.md
I think the warning session can be removed because the relative issues is resolved.
https://github.com/nushell/nushell/issues/15561
https://github.com/nushell/nushell/issues/15416
> Remove note about issue #15326

- book/custom_completions.md
Since https://github.com/nushell/nushell/pull/15511 deprecates `positional`, this PR removes mentions of that option from the page on custom completions. Also adds that `completion_algorithm` can be set to `substring`.
> Don't mention positional on custom completer page

- lang-guide/chapters/types/basic_types/closure.md
- make_docs.nu
Now uses the data directly from `help {command}` to ensure that the table
is fully populated by all input/output combinations.
Is meant to address https://github.com/nushell/nushell.github.io/issues/1931
However, it is lacking in that it now is not clear which of the IO pairs is the default etc (details found when inspecting with `scope commands`. However, `scope commands` instead hides details when applying deduping logic
```scope.rs
sigs.dedup_by(|(k1, _), (k2, _)| k1 == k2);
```
> feature(make_docs.nu): adjust the input/output section generation

- book/custom_completions.md
- cookbook/external_completers.md
> Move zoxide completer from external_completers to custom_completions

- book/custom_commands.md
Fixing a simple typo in the Nushell book.
> Fix typo in custom_commands.md

- blog/2025-05-23-twin0300.md
> Twin 0300.md

- blog/2025-06-10-nushell_0_105_1.md
by opening PRs against the `release-notes-0.105.1` branch.
> Release notes for `0.105.1`

- book/variables.md
Usage:
`generate <closure> (initial)`
The following code example does `generate (initial) <closure>` instead, which is incorrect.
> Fix erroneous Nu code in variables.md

- book/coloring_and_theming.md
This is a follow up of nushell/nushell#16013. Its PR template says to update this documentation after the PR is merged.
This also adds missing new-ish `'single'` table mode.
One issue is that I am not sure if this is appropriate to merge right away, as `'double'` mode is for yet-not-released 0.106.0 version. If you want, I can split this PR into two: one adding `'single'` (which can be merged now) and one for `'double'` (for later).
> feat: update available table modes

- book/types_of_data.md
Filter was deprecated in 0.105.0
> fix: Getting started documentation now uses where instead of filter

- book/background_jobs.md
So readers can easily see the progress of this feature.
> docs: add link to issue

- README.md
Add links to the documentation sections, right after installation instructions, to guide users into them, and give them a short overview.
The sections Design Notes and Advanced are not included here. They are not significant for new or unfamiliar users, and remain discoverable within the documentation book.
Resolves #1952
> Add doc section and links to home page

- cookbook/setup.md
> Improve cookbook setup env setup

- lang-guide/chapters/types/basic_types/closure.md
> Link commands in lang-guide closure command list

- book/configuration.md
The old code produces "/home/user/.local/share/nushell/nushell/completions", which is wrong with double "nushell".
> Fix completions folder path

- lang-guide/chapters/types/basic_types/closure.md
In this section of the language reference we want to explore and demonstrate examples of variance of use.
The unnecessary layout separation (headlines, horizontal line separators) and command elaboration took away from that. This change focuses the examples into demonstrating different closure use cases and behaviors in the context of commands.
It also adjusts the examples to have one code block with input and output.
It also improves some code examples, like the sort-by actually doing some sorting, demonstrating.
With the sometimes adjusted examples and documented output, the closure behavior does not need the redundant explanation.
Relates to #1929
> Reduce and focus closure command examples

- book/default_shell.md
- book/getting_started.md
- book/installation.md
This is a follow-up to PR #1985
> Add prev next nav refs to install child

- README.md
- book/hooks.md
- book/installation.md
> Update winget install guide

- cookbook/foreign_shell_scripts.md
Line splitting was less safe as some scripts inject `BASH_FUNC_...` env variables which have newlines in them
> Use null character ending with env

- book/line_editor.md
Also to make this consistent with other parts of the same page, such as
https://github.com/nushell/nushell.github.io/blob/6b4312b1a329498756af4d02c45a03b78a279056/book/line_editor.md?plain=1#L122-L124
> book: write Control key as just «Ctrl», not «Ctrl>»

- blog/2025-07-30-nushell_0_106_1.md
- blog/2025-08-30-nushell_0_106_1.md
by opening PRs against the `release-notes-0.106.1` branch.
[deprecations]: https://github.com/nushell/nushell/labels/deprecation
[removals]: https://github.com/nushell/nushell/pulls?q=is%3Apr+is%3Aopen+label%3Aremoval-after-deprecation
> Release notes for `0.106.1`

- book/operators.md
In [Programming in Nu#Operators:262](https://github.com/nushell/nushell.github.io/blob/22957e0164847926d9ea0b6f83d97ddd9626f73b/book/operators.md?plain=1#L262) inferring the arguments from the list position could introduce some misunderstanding.
This PR is a result of my own misunderstanding (see issue #2003) in how a list was spread. I recognize that my misunderstanding was not a result of a lack of clarity, but that I simply did not understand how it operated, and had not properly scrutinized the following examples.
However, I do believe that this makes things clearer, at the risk of being needlessly tedious. This is left for your consideration.
> Use a record instead of a list to clarify arguments in Programming in Nu#Operators examples.

- book/background_jobs.md
See also https://github.com/nushell/nushell/pull/16372/
> Document how to use `job send` and `job recv`

- blog/2025-09-02-nushell_0_107_0.md
This PR will update #1999 
I made a bad assumption when filling out the new PR template
> 0.107.0 release ntoes: Fix incorrect tense in release notes entry

- .vuepress/config.js
- blog/2025-09-02-nushell_0_107_0.md
- typos.toml
by opening PRs against the `release-notes-0.107.0` branch.
> Release notes for `0.107.0`

- make_docs.nu
Example screenshot of constructed error case:
Resolves #2010
---
I would have preferred an error exit, but I'm not sure how to do that in a way that it works for this script both when calling it as a script via `nu` as well as when running it via `source` then `make_docs` command.
Checking for invalid paths, reporting them and skipping them seems like a reasonable improvement, especially in the context of #2010 (runtime errors further down the script and command pipeline).
> Report and forgive missing plugins in make_docs.nu
