nushell/nushell.github.io

404.html, _includes/navigation.html, _layouts/about.html, _layouts/command.html, _layouts/default.html, _layouts/doc.html, _sass/fonts.scss, _sass/jekyll-theme-midnight.scss
=> Layout improvements

README.md, about.md, contribute.md, documentation.md, installation.md
=> update README, documentation, installation, contribute, about

_includes/navigation.html, _sass/jekyll-theme-midnight.scss
This adjusts font sizes on small screens. It makes sure the header fits in 1 line on screens that are at least 360 CSS-pixels wide.
=> Adjust for mobile devices

_includes/script.html, _sass/fonts.scss, _sass/jekyll-theme-midnight.scss, _sass/rouge-base16-dark.scss
Reverts nushell/nushell.github.io#13
I think we got closer, but something about the combination of recent PRs might be throwing it off. Reverting this PR for now, to get us back to a slightly better state. That said, let's definitely see if there's a similar solution that works.
=> Revert "Fix variable width characters in `pre`"

documentation.md
PR adds a better description of what covers Nu Cookbook
=> better cookbook description

_includes/navigation.html, _sass/jekyll-theme-midnight.scss
PR updates the navigation menu. It is now easier and more intuitive to get information on the site.
It looks as discussed in #24.
=> improve navigation

installation.md
I changed them to match what is in the book. Should fix #29
=> Update cargo flags

commands/uniq.md
=> Align tables in commands/uniq.md

documentation.md
lern -> learn
Terrific project!  Thank you! 💯
=> Corrects minor typo

book/types_of_data.md
As discussed on Discourse.
This is imperfect, but on net better than previous, and enough small improvements gets to perfect...
=> Add groups docs from @jturner

.vuepress/theme/layouts/Layout.vue, book/environment.md
Try to fix the table alignment font.
Add some more info to the environment section
=> Fix android font and update env section

CONTRIBUTING.md
Is this what you had in mind for this part of `contributing.md`? This is all I had to do to get a dev build running.
=> added basic instructions for running vuepress locally

book/types_of_data.md
Yeah, quite a ridiculous pull request, but I found this quick type typo :stuck_out_tongue:!
=> Fix typo in types_of_data.md

CONTRIBUTING.md, book/plugins.md
Found a couple of dead links that I believe were pointing towards old pages.  Updated them to point towards current locations of page contents.
=> Fix Dead Links

blog/2021-06-01-nushell_0_32.md
Just fixing a couple small mistakes I pointed out on the [reddit release post](https://www.reddit.com/r/rust/comments/nq00dr/nushell_032_lots_of_improvements_to_the_language/h08hu3g?utm_source=share&utm_medium=web2x&context=3)
=> Minor nit fixes

book/commands/where.md, book/types_of_data.md, contributor-book/values.md, es/contributor-book/valores.md, ja/book/types_of_data.md, pt-BR/contributor-book/valores.md, zh-cn/book/types_of_data.md
Addresses https://github.com/nushell/nushell/issues/3569
=> Fix duration literals in docs

book/commands/where.md
=> Fix missed mention of duration literal

book/configuration.md
Removes load file option since it doesn't exist
=> Remove config load since it doesnt exist

book/configuration.md
Fixes https://github.com/nushell/nushell/issues/3685
=> Mention how to get back `/usr/bin/open` on Mac

.vuepress/config.js, cookbook/README.md
Change the first page in the cookbook
=> cookbook page

README.md, es/README.md, ja/README.md, zh-cn/README.md
Mostly translation to spanish's main site. 
The first feature description in english feels uncomfortable:
```
Control your system with powerful pipelines
Pipelines let you command your system like never before. Your system belongs to you, and it awaits your command.
```
Rewrote it. Happy to rollback or to change it to something else, please advise. @jonathandturner
=> Main page description changes.

book/dataframes.md
A few spelling, wording and punctuation fixes; add a link to pandas.
=> Book: various tweaks to the Dataframes chapter

book/commands/count.md
Documentation needs updating for this.
https://github.com/nushell/nushell/issues/3226#issue-843663497
=> Update count.md: command `count` has been migrated to `length`

book/working_with_tables.md
I guess this got removed a while back!
=> there's no values column anymore

book/configuration.md, book/dataframes.md, book/environment.md, book/installation.md, book/loading_data.md, book/math.md, book/moving_around.md, book/pipeline.md, book/types_of_data.md, book/working_with_tables.md
Hi there,
Long-time pandas user here -- I really enjoyed working my way through the tutorials shown in this book, and hope to use a lot more of Nushell in my data analysis work! In doing the examples, I noticed some minor typos and style issues on specific pages that I felt could be made more consistent across the rest of the book. Hope this works, and thanks for the great work!
=> Fix typos + minor style changes

contributor-book/plugins.md
The actual plugin discovery approach has changed and thus the document should be updated accordingly.
=> Update plugin discovery section of the doc

book/shells_in_shells.md
Add `g` command for better shell switch.
nushell/nushell#4014
Signed-off-by: Tw <wei.tan@intel.com>
=> Add document for `g` command

cookbook/git.md
- `$it` is not defined when I ran the previous command. Added each to fix it
- added main branch
- added trim
=> Fix git rm merged

book/installation.md
Nu is also available on Scoop and Chocolatey, but I've only included Winget for now.
=> Add winget as installation method

book/regular_expressions.md, book/table_of_contents.md, contributor-book/plugins.md
Add #217. I want you to check if this is the way to do it.
=> Add regex documents

README.md
Parallel change to https://github.com/nushell/nushell/pull/4641.
=> Document Visual C++ requirement on Windows.

zh-cn/book/README.md
Update README.md with more Chinese Translations
=> Update README.md with more Chinese Translations

book/coming_from_bash.md, book/configuration.md
some tweaks to the bash section and the config section
=> Bash and config

book/dataframes.md
The file column is no longer shown in the list command
=> removed column from dfr list

cookbook/files.md, cookbook/git.md, cookbook/help.md, cookbook/http.md, cookbook/misc.md, cookbook/native_shell_programs.md, cookbook/parsing.md, cookbook/setup.md, cookbook/system.md
everything except `parsing_git_log.md` is updated. Will tackle that beast next.
=> updates to the cookbook

book/coloring_and_theming.md
Setting `without_color: false` has been changed into `use_ansi_coloring: true`.
=> Change `without_color` to `use_ansi_coloring`

.gitignore, i18n-meta.json, i18n.nu
Add i18n related script and meta data
=> Add i18n related script and meta data

book/environment.md
Updates the section about environment conversions.
=> Update env conversions

book/commands/default.md, book/commands/do.md, book/commands/empty.md, book/commands/ls.md, book/commands/match.md, book/commands/open.md, book/commands/reduce.md, book/commands/where.md
=> Update docs for commands

book/nushell_operator_map.md
=> Add Pwsh 7 && and || to operator map page

.vuepress/config.js, package.json
- Remove unused VuePress search config now that we're using Algolia for search
- Clean up `package.json` a bit
=> Search and package.json cleanup

book/commands/insert.md, book/commands/update.md, book/commands/upsert.md, book/working_with_tables.md
=> Update insert/update/upsert docs

.vuepress/config.js
I just commented out all the contributor book references in the config.js. I did not remove references to it in the md files.
=> temporarily remove the contributor book until we can get it updated

i18n-meta.json, i18n.nu
Update i18n releated scripts and meta data
=> Update i18n releated scripts and meta data

book/dataframes.md, book/types_of_data.md
Removes `$true`/`$false` in favour of `true`/`false`
=> remove the boolean vars

book/make_docs.nu
Update make_docs.nu, add directory check
=> Update make_docs.nu, add directory check

book/scripts.md
I had some questions about how the special `main` command works in scripts. Tweaking the docs to demystify `main` a bit and also fix up the examples.
=> Fix up Parameterizing Scripts

book/plugins.md
The Plugins page was very bare-bones. Adding some info to explain how plugins work in broad strokes.
This could use a review from someone who's worked with plugins before.
=> Update Plugins page in book

book/3rdpartyprompts.md
Update oh-my-posh setup guide for mac users
=> Update oh-my-posh setup guide for mac users

ja/book/configuration.md
Could not transition to the url
https://starshp.rs
↓
https://starship.rs
=> Fix Typo Starship URL

book/commands/sort-by.md, book/loading_data.md, book/thinking_in_nushell.md, book/types_of_data.md
Update examples for sort-by, fix some examples, change column names to lowercase
=> Update examples for sort-by, fix some examples

book/pipeline.md, book/working_with_tables.md
=> Fix some errors

book/scripts.md
=> Move the "main" word outside of code block

book/line_editor.md, book/plugins.md
=> Some small fix

book/types_of_data.md
Add record to table example using `transpose`
Very simple example :)
=> Add record to table example

book/README.md, zh-cn/book/README.md, zh-cn/book/table_of_contents.md
Translate table of contents and README to zh-CN from commit: c13a71d11
=> Translate table of contents and README from commit: c13a71d11

book/coming_from_bash.md, book/dataframes.md, book/installation.md, book/line_editor.md, book/types_of_data.md, zh-cn/book/installation.md
Translate installation to zh-cn from commit: c13a71d11
And do some docs formatting
=> Translate installation to zh-cn from commit: c13a71d11

de/README.md, i18n-meta.json
Match mainpage for german translation with english version and update `i18n-meta.json` according to #261.
=> update main page [german]

de/README.md, de/book/3rdpartyprompts.md, de/book/README.md, de/book/installation.md, de/book/konfiguration.md, de/book/von_bash_kommend.md
- Update prompt docs
- Fix command table
- Small typos, style etc.
=> Fix several parts in the German edtion

book/line_editor.md
Introduced unbinding with nushell/nushell#5152
=> Document unbinding a keybinding

book/types_of_data.md
Can be published after the nushell version including
Issue https://github.com/nushell/nushell/issues/4924
PR https://github.com/nushell/nushell/pull/5149
was released.
=> nushell#4924 Update data types with binary literal syntax

.vuepress/config.js, book/scripts.md, i18n-meta.json, zh-CN/book/modules.md, zh-CN/book/scripts.md
Translate scripts and modules to zh-CN from commit: 115b193d2
=> Translate scripts and modules to zh-CN from commit: 115b193d2

book/configuration.md
Also reworded a bit to reflect that we have two config files now.
=> Add env.nu to Configuration

.vuepress/config.js, book/coloring_and_theming.md, i18n-meta.json, zh-CN/book/coloring_and_theming.md
Translate coloring_and_theming.md to zh-CN from commit: f3dc86d3d
=> Translate coloring_and_theming.md to zh-CN from commit: f3dc86d3d

CONTRIBUTING.md
=> Add translation guide

.vuepress/config.js, i18n-meta.json, i18n.nu, zh-CN/book/dataframes.md
Translate dataframes.md to zh-CN from commit: 92fb0ac2c
=> Translate dataframes.md to zh-CN from commit: 92fb0ac2c

README.md, zh-CN/README.md
Add github action related stuff
=> feat: Add github action related stuff

CONTRIBUTING.md, i18n-meta.json, zh-CN/book/coloring_and_theming.md
=> Update zh-CN docs

blog/2022-05-03-nushell_0_62.md
Just adding some info to demo the new SQLite functionality a bit more. Let me know if you'd prefer to keep it short+sweet, I don't mind reverting this.
=> Update SQLite bits in 0.62 blog post

book/custom_commands.md, book/pipeline.md
There’s no mention of `$in` in the book so far, let’s fix that.
=> Document $in

book/environment.md
Also clarifies environment hiding.
=> Add env.nu to env conversions section

.vuepress/config.js, i18n-meta.json, zh-CN/README.md
Update zh-CN home page and keep the Chinese and English docs in sync
=> Update zh-CN home page and keep the Chinese and English docs in sync

blog/2022-05-24-nushell_0_63.md
Was still a todo in the 0.63.0 notes
=> Mention the `nu` flags in the release notes

overlays.md
Just a stub for an eventual Overlays book chapter.
=> Create overlays.md stub

book/overlays.md
Adds a tip about the new `overlay new` command.
=> Add 'overlay new' tip

book/dataframes.md
=> lazyframes section

book/environment.md
closes #464
@sholderbach I made you the author, as I basically took what you wrote in nushell/nushell#5684 and #464
=> Add 'Reading environment variables' section

book/custom_commands.md
=> Add documentation for switch flags

.gitignore
=> Trigger deploy workflow

.vuepress/styles/index.scss
Fix search box style, make it align left
=> Fix search box style, make it align left

.vuepress/styles/index.scss
Fix search box style, make it wider
=> Fix search box style, make it wider

.vuepress/config.js
fix feed plugin add atom support
=> fix feed plugin add atom support

.vuepress/styles/index.scss
Fix responsive layout for mobile devices
=> Fix responsive layout for mobile devices

.vuepress/styles/index.scss
Fix responsive layout for more screen size
=> Fix responsive layout for more screen size

book/working_with_strings.md
=> Add more documentation about strings

.vuepress/config.js, package.json
feat: Add sitemap generator to create sitemap.xml
=> feat: Add sitemap generator to create sitemap.xml

.vuepress/config.js, package.json
fix feed plugin configs, make it work as expected
=> fix feed plugin configs, make it work as expected

.github/workflows/deploy.yml
Fix checkout step for feed plugin
=> Fix checkout step for feed plugin

.github/workflows/deploy.yml
Reverts nushell/nushell.github.io#485
=> Revert "Fix checkout step for feed plugin"

.github/workflows/deploy.yml
fix: update deploy workflow for checkout
=> fix: update deploy workflow for checkout

book/coming_from_bash.md
`str find-replace` is deprecated and no longer functional
=> Replace `str find-replace` with `str replace` in `coming_from_bash.md`

.vuepress/config.js, book/table_of_contents.md, ja/README.md, zh-CN/book/table_of_contents.md
=> Fix some broken links

book/configuration.md, book/working_with_strings.md
Just fixing a couple of typos I noticed while going through the nu book.
=> Fix a couple of typos

de/book/environment.md, de/book/moving_around.md, de/book/thinking_in_nushell.md, de/book/types_of_data.md
Some files with translation and new snippet links.
=> Some new German translation with new snippet links

book/types_of_data.md
Took me a minute crawling the Commands Reference to see how to cast between types.  Added some helpful info in the docs about it
=> Show how to cast between number types

book/coming_from_bash.md
- `chmod` is totally a thing
- Line continuations have been supported for a while
=> docs(book): Update the "Coming from Bash" page

de/book/environment.md, de/book/moving_around.md, de/book/thinking_in_nushell.md, de/book/types_of_data.md
=> Fix some broken links for de

.vuepress/components/BlogPosts.vue
fix blog layout and font color of article title for dark mode
=> fix blog layout and font color of article title for dark mode

book/configuration.md, zh-CN/book/configuration.md
Add built-in config command -> `config nu` and `config env` for both English and Chinese
=> Add configuration command

.vuepress/config.js, book/overlays.md, i18n-meta.json, zh-CN/book/overlays.md
Translate overlays.md to Chinese
=> Translate overlays.md to Chinese

book/coloring_and_theming.md
Add light theme description to handle https://github.com/nushell/nushell/issues/5961
=> add light theme relative doc

package.json
update vuepress and related plugins
=> update vuepress and related plugins

.vuepress/config.js, CONTRIBUTING.md, book/hooks.md, book/table_of_contents.md
This PR adds a new page about hooks with some examples.
Also adds some comments to the local deploy steps for web noobs such as myself.
=> Add hooks documentation

i18n-meta.json, zh-CN/book/coloring_and_theming.md, zh-CN/book/moving_around.md
Update zh-CN translation for moving_around and theming
=> Update zh-CN translation for moving_around and theming

book/loading_data.md
This PR adds some bare-bones documentation about loading data using SQLite. I should have written this up many months ago!
=> Document SQLite data loading

book/stdout_stderr_exit_codes.md
Simple edit to make sentence more concise.
=> chore: small edit

CONTRIBUTING.md
It is not in sync with https://github.com/nushell/nushell.github.io/blob/b2fc46f3d72c11f9fa29aa7dcb55c33ac41768e0/.github/workflows/ci.yml#L15
=> docs: contributing workflow is outdated

book/modules.md
This PR fixes a minor typo in the `book/modules.html` page. Only a repeated word :ok_hand: :wink:
=> FIX: there is a minor typo in the modules page

book/custom_commands.md, de/book/eigene_befehle.md, zh-CN/book/custom_commands.md
List all current supported types for custom command signatures (note: since 0.65.0).
ty.
=> Update accepted types for signatures

package-lock.json, package.json
Upgrade vuepress and all related plugins to improve build performance, more detail: https://github.com/vuepress/vuepress-next/blob/main/CHANGELOG.md#performance-improvements
=> Upgrade vuepress and all related plugins to improve build performance

i18n.nu
Account for nushell/nushell#6464
=> Update i18n script to `is-empty` name change

book/plugins.md
Reflect to changes in https://github.com/nushell/nushell/pull/6486
=> update plugin for newest changes

cookbook/misc.md
Following the suggestion of #2812.
=> Cookbook : SSH passphase management

book/plugins.md
Update doc to reflect changes on https://github.com/nushell/nushell/pull/6479
=> add doc about plugin name

blog/2020-06-30-nushell_0_16_0.md, blog/2020-08-11-nushell_0_18.md, book/coming_from_cmd.md, book/commands/ansi.md, book/commands/ansi_strip.md, book/commands/char.md, book/commands/str_collect.md, book/commands/upsert.md, book/configuration.md, book/custom_commands.md, book/environment.md, book/line_editor.md, book/make_docs.nu, book/nushell_map.md, book/nushell_map_functional.md, book/nushell_map_imperative.md, book/stdout_stderr_exit_codes.md, de/book/environment.md, de/book/konfiguration.md, zh-CN/book/configuration.md, zh-CN/book/custom_commands.md, zh-CN/book/environment.md, zh-CN/book/line_editor.md, zh-CN/book/nushell_map.md, zh-CN/book/nushell_map_functional.md, zh-CN/book/nushell_map_imperative.md, zh-CN/book/stdout_stderr_exit_codes.md
For merge into a release branch; see https://github.com/nushell/nushell/pull/6531
=> `str collect` => `str join`

blog/2022-09-27-nushell-0_69.md
Please contribute your major changes to the relase notes on the `release_notes_69` branch.
Currently just a stub
=> [WIP] Release notes for 0.69

book/moving_around.md, book/nu_fundamentals.md, book/types_of_data.md, book/working_with_strings.md
Some copy-editing of the initial book sections. I'll add some comments in-line explaining the changes where they're not obvious.
=> Some copy editing of initial book sections 

book/coming_from_bash.md
Closes https://github.com/nushell/nushell/issues/6656
=> Add example of inline string concat

snippets/moving_around/ls_deep_glob_example.sh
Remove hidden files from the result of `ls` command. It doesn't seem to output hidden files.
=> Fix a sample code on the "moving around" chapter

blog/2022-10-18-nushell-0_70.md
Please add your important new features and breaking changes to the release notes by commiting to/opening a PR against the `release-notes-0.70` branch! Thanks for helping out!
=> Release notes for nushell 0.70

blog/2022-11-08-nushell-0.71.md
😄 
PR: https://github.com/nushell/nushell/pull/6904
=> docs: documents the changes to mv (branch release 0.71)

book/3rdpartyprompts.md
Original link is dead. Replaced with new URL.
=> Update oh-my-posh install link

blog/2022-11-08-nushell-0.71.md
Document change from PR #7007 with column name rename.
=> docs: document changes from #7007

book/hooks.md
Document the new display_output hook in the hooks chapter.
=> Document display_output hook

book/getting_started.md
Page: https://www.nushell.sh/book/getting_started.html
Link: https://www.nushell.sh/book/moving_around/md
Fixed typo  s/`/``.` https://www.nushell.sh/book/moving_around.md
=> fix 404 link

contributor-book/philosophy_0_80.md
This is very much a work-in-progress and welcomes comments.
=> Create a section for the 0.80 philosophy

blog/2022-11-29-nushell-0.72.md
documentation for `url parse` command
https://github.com/nushell/nushell/pull/7124
=> document `url parse` command

blog/2022-11-29-nushell-0.72.md
See https://github.com/nushell/nushell/pull/7198.
=> Release Notes: add note about `--ignore-case`

blog/2022-11-29-nushell-0.72.md
Note that the advice for "output your existing options" is liable to change based on whether Nushell issue nushell/nushell#7059 is implemented or not. That section is preliminary.
=> Add config.nu structure changes

book/operators.md
Include `++` list append, `xor`.
Polish table
Expand operator precedence.
=> Update operator docs

book/types_of_data.md
Autoformatting as mentioned in #670
=> Autoformat book/types_of_data.md

.vuepress/configs/sidebar/en.ts, book/command_signature.md, book/programming_in_nu.md
Reflect to nushell pr: https://github.com/nushell/nushell/pull/7079
=> add command signature section

book/make_docs.nu
Optimize make_docs script for better performance, the docs output keeps unchanged
=> feat: optimize make_docs script for better performance

package-lock.json, package.json
Upgrade some outdated dependencies
=> chore: Upgrade some outdated dependencies

blog/2022-12-20-nushell-0.73.md
Related to https://github.com/nushell/nushell/pull/7462
=> `mkdir` `--show-created-paths` flag replaced

book/working_with_tables.md
the example of `merge` command was incorrect
=> Correct command examples

book/custom_completions.md
=> custom completion: added external_completer

blog/2022-12-20-nushell-0.73.md
Please add your important new features and breaking changes to the release notes by committing to/opening a PR against the `release-notes-0.73` branch. Thank you!
=> [WIP] Release notes for `0.73`

book/working_with_tables.md
=> clarify columns and rows

book/make_docs.nu
Update book/make_docs.nu for nu v0.72.1+
=> Update book/make_docs.nu for nu v0.72.1+

book/make_docs.nu
Fix book/make_docs.nu for nu v0.73+
=> Fix book/make_docs.nu for nu v0.73+

i18n-meta.json, i18n.nu
fix i18n.nu script and update i18n-meta conf
=> fix i18n.nu script and update i18n-meta conf

.vuepress/configs/sidebar/de.ts
=> Fix #705: sidebar links German.

.vuepress/configs/navbar/en.ts
Sorry I'm not really good at web page, so in this pr I just try to change text `Blog` to `Changelog` and see if it's working
=> Try to rename from blog text to changeLog

.vuepress/config.js
Closes #739. We should definitely not attempt to prefetch every page on the website...
=> Disable prefetch setting

blog/2023-01-31-nushell_0_75.md
=> Add my changes

.github/workflows/typos.yml, .typos.toml, book/commands/split-by.md, book/explore.md, book/hooks.md, book/how_nushell_code_gets_run.md, book/loading_data.md, contributor-book/philosophy_0_80.md
- Add Github Actions workflow to check typos
- Fix existing typos
=> Add Github Actions workflow to check typos

book/types_of_data.md
This change was introduced on 0.72
=> Reflect the separation of block and closure

package-lock.json, package.json
[Update some vuepress plugins](https://github.com/nushell/nushell.github.io/pull/771/files)
=> Update some vuepress plugins

blog/2023-02-21-nushell_0_76.md
=> release notes for #7952

.vuepress/config.js, blog/README.md, package-lock.json, package.json
fix #781 and update some node modules
=> fix #781 and update some node modules

zh-CN/book/loading_data.md
fix #768 for zh-CN translation
=> fix #768 for zh-CN translation

commands/docs/registry_query.md
Add registry query doc for Windows
=> Add registry query doc for Windows

book/working_with_lists.md
Hi, 
While reading documentation, I thought the removing items from lists were missing from that part of the documentation, and thought adding it couldnt be harmful. 
Totally cool is this is deemed a bit extra or not necessary. Cheers
=> Expand working with lists description

book/configuration.md, snippets/installation/remove_welcome_message.nu
the config option to disable banner is show_banner, not show-banner
That does not leave a great impression when the first thing read in documentation is incorrect...
=> Fix show_banner config item

blog/2023-03-14-nushell_0_77.md
Please add your important new features and breaking changes to the release notes by committing to/opening a PR against the `release-notes-0.77` branch. Thank you!
=> Release notes for `0.77`

.vuepress/configs/sidebar/en.ts, book/advanced.md, book/programming_in_nu.md, book/standard_library.md, book/testing.md
Also a draft for standard library.
For being complete it is needed to have the command pages generated automatically from standard library, as they are for the built-in commands.
=> Add chapter about testing in Nushell

book/hooks.md
This PR adds docs on the `command_not_found` hook, with an example in *Arch Linux*.
=> feat: docs on the `command_not_found` hook

book/coloring_and_theming.md, book/line_editor.md, de/book/coloring_and_theming.md, de/book/konfiguration.md, zh-CN/book/coloring_and_theming.md, zh-CN/book/line_editor.md
This PR updates all occurrences of `let config` to `let-env config`.
=> change `let config` to `let-env config`

blog/2023-04-04-nushell_0_78.md
I found a small syntax error while looking at this blog post. I glanced through the rest of the code examples too but nothing else stuck out to me
=> Fix syntax error in blog post

book/line_editor.md
The commit 0ea7a38c21d3c365afdd86f3b9a329938dc99b8 change the keybinding to F1
=> Fix old keybding for help menu

book/working_with_tables.md
adding reject into "working with tables"
=> Update working_with_tables.md to include reject

book/dataframes.md
Ensure that every Nushell command can be executed.
=> Dataframes

book/testing.md
- setup, teardown methods
- use built-in std library notation
=> Update testing chapter

book/variables_and_subexpressions.md
this pr updates variable documentation.
it touches on
- types of variables
- assignment syntax
- question mark operator on cell paths
=> update variable documentation

blog/2023-04-25-nushell_0_79.md
as there is so much work done and so many things to talk about, i tried to keep that simple :relieved:
=> add the note about the standard library

README.md, book/installation.md
Update npm install instruction
=> Update npm install instruction

book/aliases.md
Fixing small typo that broke formatting on last few paragraphs of the page
=> Fixing Tiny Typo - Update aliases.md

book/coming_from_bash.md
hi, I tried to use `hide` for an env var and it didn't work
=> book/coming_from_bash - s/hide/hide-env

blog/2023-05-16-nushell_0_80.md
hello there :yum: 
i've looked at [all the PRs from last release to today](https://github.com/nushell/nushell/pulls?q=is%3Apr+is%3Amerged+merged%3A2023-04-25..2023-05-09T19%3A30) and added links to them in this PR :relieved:  
there not much text and i've left the PR editable by any of you guys :smile:
=> add a bunch of interesting PR links

book/dataframes.md
just a missing `\n` before the code block...
=> small typo in `dataframes.md`

blog/2023-05-16-nushell_0_80.md
by opening PRs against the `release-notes-0.80` branch.
=> Release notes for `0.80`

blog/2023-05-16-nushell_0_80.md
=> Tiny typo fixes in 2023-05-16-nushell_0_80.md

book/custom_commands.md, book/environment.md, book/modules.md, book/overlays.md
Reflects https://github.com/nushell/nushell/pull/9066
=> Update modules chapter

blog/2022-03-01-nushell_0_59.md
Remove unnecessary 0.59 binaries, It's old and outdated
=> Remove unnecessary 0.59 binaries

i18n.nu
This is a **Tracking PR** for the Nushell Docs Repo Cleanup Task
1. After the cleanup only one branch will be kept, that's the `main` branch
2. The commit history will be kept but all the commit ids will be changed after cleanup
3. The [nushell.sh](http://nushell.sh/) site maybe unavailable for a while, from quite a few minutes to maybe an hour
4. We won’t accept any PR when the cleanup process starts until it’s finished
Close https://github.com/nushell/nushell.github.io/issues/924
=> Nushell Docs Repo Cleanup Plan

ja/book/nushell_map_functional.md
=> Fix missing `|`

blog/2023-06-06-nushell_0_81.md
by opening PRs against the `release-notes-0.81` branch.
=> Release notes for `0.81`

blog/2023-06-27-nushell_0_82.md
Related to [#9407](https://github.com/nushell/nushell/pull/9407) and #945
=> chore: add detail to breaking changes

book/aliases.md, cookbook/setup.md, de/book/aliase.md
- Add an example how to set the EDITOR variable in env.nu to setup.md
- Update misleading/confusing section about persisting aliases to aliases.md + german translation
- Added some info about pipes in aliases + german translation
=> Update aliases.md and setup.md

book/custom_commands.md
Clarify that flags with dashes are allowed and how to access them.
=> Flags with dashes

blog/2023-06-27-nushell_0_82.md
Please help out by adding your major new features and any breaking changes to the release notes by opening PRs against the `release-notes-0.82` branch.
Thank you very much!
=> Release notes for `0.82.0` release

blog/2023-06-27-nushell_0_82.md
=> Fix typo in 2023-06-27-nushell_0_82.md

blog/2023-07-25-nushell_0_83.md
by opening PRs against the `release-notes-0.83` branch.
=> Release notes for `0.83`

book/3rdpartyprompts.md
I updated the oh-my-posh setup guide as the previous one did not seem to work for me. I hope this helps! This is my first ever contribution to a project outside of school. Looking forward to maybe contributing more.
=> Updated the oh-my-posh setup guide

blog/2023-07-25-nushell_0_83.md
this PR simply uses real markdown hyperlinks to link to the GitHub pages of the contributors in the *shoutout* section :yum:
=> give real links to our GitHub contributors

de/book/installation.md, ja/book/installation.md, package-lock.json, package.json, zh-CN/book/installation.md
Upgrade some dependencies, and fix some broken assets import: It's found that there is no `snippets/installation/crates_run_nu.sh` file at all
=> Upgrade some dependencies, and fix some broken assets import

book/nushell_map_functional.md
This PR removes an empty column from book/nushell_map_functional.
=> Remove unused empty column

de/book/environment.md, de/book/konfiguration.md
=> Finish `let-env` removal in German translation

zh-CN/book/configuration.md, zh-CN/book/environment.md, zh-CN/book/modules.md
Finish `let-env` removal in Chinese translation
=> Finish `let-env` removal in Chinese translation

book/aliases.md
https://github.com/nushell/nushell/issues/9011#issuecomment-1679486217
=> Update command to list aliases

book/coloring_and_theming.md
Update table mode config doc, fix #1007
=> Update table mode config doc, fix #1007

blog/2023-08-22-nushell_0_84_0.md
=> Sections for release notes

book/coloring_and_theming.md
Related to https://github.com/nushell/nushell/pull/10122, this PR creates an accessibility subsection explaining recommended settings for screen reader users.
=> Error style section

book/shells_in_shells.md
related to https://github.com/nushell/nushell/issues/9486
=> Update docs for exiting shell in shells

cookbook/setup.md
so it can be used inside config.nu as well
=> Cookbook setup: fix command to append to PATH

contributor-book/plugins.md
…This PR will ssolve Issue 1059. Change Python example in Plugins chapter shebang line to be more portable.
=> Changed Python plugin example to be more portable

blog/2023-09-19-nushell_0_85_0.md
Seems like vuepress doesn't autoconvert them
=> Change to an actual link in last blog post

book/programming_in_nu.md
This is a small typo correction
=> correct typo

book/configuration.md, lefthook.yml
=> Fix code formatting hooks

book/3rdpartyprompts.md, book/background_task.md, book/coloring_and_theming.md
I've ran https://lychee.cli.rs and it found a couple of broken links
=> Fix broken links

cookbook/pattern_matching.md
Of course right after landing my previous PR I see that I left a sentence unfinished. Whoopsie 😅 This PR finishes it, and also adds a small example about overlapping match arms for folk perhaps unfamiliar with it.
=> finish sentence in pattern matching.md

blog/2022-10-18-nushell-0_70.md, blog/2022-11-08-nushell-0.71.md, blog/2022-11-29-nushell-0.72.md, blog/2022-12-20-nushell-0.73.md, blog/2023-01-10-nushell_0_74.md, blog/2023-01-31-nushell_0_75.md, blog/2023-02-21-nushell_0_76.md, blog/2023-03-14-nushell_0_77.md, blog/2023-04-04-nushell_0_78.md, blog/2023-08-23-happy-birthday-nushell-4.md
Update syntax highlighting for some blog docs
=> Update syntax highlighting for some blog docs

CONTRIBUTING.md, lefthook.yml, package-lock.json, package.json
Update CONTRIBUTING.md and lefthook module, Please run `npm install` after pull
=> Update CONTRIBUTING.md and lefthook module

cookbook/setup.md
@amtoine meant that something like this could be a nice addition to the cookbook.
I personally use this as the example I gave in here.
=> Added "Use hooks to export state via environment variables" Section in setup.md

blog/2023-10-17-nushell_0_86.md
meaning: within the uutils/coreutils project / codebase
=> Nushell 0.86 release notes: fix grammar "made their"→"made there"

snippets/book/std_log.nu
Title says it all.
Fixes  #950
=> Update outdated std log import in `std_log.nu`

book/types_of_data.md
Update `Decimals` text with the recent `into float` change
Fixes broken link and clarifies correct command.
=> Update types_of_data.md with "into float"

book/scripts.md
This adds a section to the script to describe how to use sub.commands
=> Book scripts with sub-commands

book/scripts.md
Documents behavior behind issue: https://github.com/nushell/nushell/issues/10887
=> Add Argument Type Interpretation to Scripts

book/pipelines.md
=> Fix broken link

.vuepress/configs/navbar/en.ts
This pr reverts #732 according to @amtoine 's comments
=> Rename back from `Changelog` to `Blog`

.vuepress/configs/sidebar/en.ts, cookbook/jq_v_nushell.md
Hi, this PR adds a new cookbook comparing jq and nushell as suggested by @fdncred in https://github.com/arnau/seachess/issues/35
I translated my original blog post using a hopefully  better outline for incrementally introduing new Nushell commands and concepts.
I would appreciate an extra eye on the written English. I'm not a native speaker so I'm sure I've done at least some silly mistakes. 🙇
=> Add a cookbook comparing jq and nushell

book/variables_and_subexpressions.md
Replaced an outdated `**=` operator with the current `++=`.
=> Fix append to mutable variable operator

blog/2023-12-12-nushell_0_88_0.md
by opening PRs against the `release-notes-0.88.0` branch.
=> Release notes for `0.88.0`

book/moving_around.md
from https://github.com/nushell/nushell/issues/10749#issuecomment-1768817807:
> Yep, no glob documentation in the book, perhaps you'd like to take a crack at writing it?
=> Extend globbing section in moving_around.md

book/custom_commands.md
follow-up to
- https://github.com/nushell/nushell/pull/11365
=> add information about switches

blog/2024-01-09-nushell_0_89_0.md
Added a section about the spread operator being supported in command calls
=> Add info on spread operator in commands for 0.89 release notes

book/aliases.md
Adding a new section of how to "replace" a command with an alias.
This might not be "best practice" but I found this solution like many other had asked before me on Discord.
That I thought could be good to have in the documentation.
This is my first commit to this projects so I thought I keep it simple to begin with.
=> Update aliases adding new section

.vuepress/configs/navbar/ja.ts, .vuepress/configs/sidebar/ja.ts
I've revised the Japanese translation as it was somewhat off, ensuring it now feels more natural and accurate.
=> I've revised the Japanese translation

ja/book/installation.md
Update the Japanese translation of installation.md catching up with English ver.
=> JA update installation.md

blog/2024-01-09-nushell_0_89_0.md
by opening PRs against the `release-notes-0.89.0` branch.
- https://github.com/nushell/nushell/pull/11131
- https://github.com/nushell/nushell/pull/11157
- https://github.com/nushell/nushell/pull/11284
=> Release notes for `0.89.0`

cookbook/external_completers.md
See https://github.com/nushell/nushell/pull/11547
=> Fix deprecation in external_completers.md

.vuepress/configs/sidebar/ja.ts, i18n-meta.json, ja/book/quick_tour.md
Add a Japanese translation of quick_tour.md
=> JA Translate quick_tour.md to ja from commit: fcf0d7c8

.vuepress/configs/navbar/en.ts, .vuepress/configs/sidebar/en.ts, lang-guide/README.md, lang-guide/lang-guide.md
This PR adds _the start_ of a language guide. Definitely `HELP WANTED` to complete this guide. Please submit PRs to fill out the sections or add new sections. The guide was written about a year ago so parts of it could be out of date.
=> add language guide

.vuepress/config.js, .vuepress/configs/navbar/index.ts, .vuepress/configs/navbar/ru.ts, .vuepress/configs/sidebar/index.ts, .vuepress/configs/sidebar/ru.ts, i18n-meta.json, i18n.nu, ru/README.md, ru/book/README.md
Add basic config and pages for Russian language
=> Add basic config and pages for Russian language

package-lock.json, package.json
Upgrade shiki syntax highlighter
=> Upgrade shiki syntax highlighter

book/dataframes.md, book/hooks.md, book/types_of_data.md, lang-guide/lang-guide.md
=> Remove $nothing

blog/2024-02-06-nushell_0_90_0.md
by opening PRs against the `release-notes-0.90.0` branch.
=> Release notes for 0.90.0

blog/2024-02-06-nushell_0_90_0.md
Other whitespace changes are due to one of the git hooks I think.
=> Escape false <int> HTML element

blog/2024-02-06-nushell_0_90_0.md, book/how_nushell_code_gets_run.md, book/thinking_in_nu.md, book/variables_and_subexpressions.md, book/working_with_strings.md
by opening PRs against the `release-notes-0.90.0` branch.
=> Release notes for `0.90.0`

lang-guide/lang-guide.md
This is a follow up to https://github.com/nushell/nushell/pull/11708
Which introduces all rules to redirections and pipes
=> fill contents to handling stderr

lang-guide/lang-guide.md
I know the document is still very WIP.
=> Some cleanup of lang-guide.md

contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
=> Add documentation for Goodbye in plugin protocol

blog/2024-03-05-nushell_0_91_0.md
* Plugin protocol overhaul
* `tee` command
* `interleave` command (PR not yet merged, but probably will be today)
* `zip` accepts closures
=> Release notes for @devyn's PRs for 0.91.0

blog/2024-03-05-nushell_0_91_0.md
by opening PRs against the `release-notes-0.91.0` branch.
=> Release notes for `0.91.0`

cookbook/direnv.md
=> Corrected link to direnv nu_script config

contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
Merge after nushell/nushell#12029
=> Documentation for engine calls

blog/2024-03-05-nushell_0_91_0.md
Someone mentioned a broken ToC on Discord
=> Fix release note toc

book/plugins.md, contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
Merge after nushell/nushell#12064
=> Documentation for plugin persistence

book/plugins.md
More comprehensive plugin installation instructions that should be beneficial especially for newcomers.
=> Update plugins.md (#12146)

contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
Docs for nushell/nushell#12088
=> Custom value ops documentation

contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
Documentation for these PRs:
- nushell/nushell#12166
- nushell/nushell#12204
=> Env var plugin engine calls docs

lang-guide/lang-guide.md
This PR just tweaks some formatting.
=> some formatting tweaks to the language guide

lang-guide/lang-guide.md
I found a few more things to tweak
=> a few more tweaks

contributor-book/plugins.md
Docs for nushell/nushell#12170
=> Plugin command api doc updates

blog/2024-04-02-nushell_0_92.md
Mostly plugin stuff, except `ignore`.
I might have more to add before release, but figured it might be good to get these in now.
=> Release notes for 0.92.0 for @devyn so far

blog/2024-04-02-nushell_0_92.md, typos.toml
Adds notes for changes from [#11934](https://github.com/nushell/nushell/pull/11934).
=> Edit release notes

blog/2024-04-02-nushell_0_92.md
More release notes.
- Plugin command API updates, including `LabeledError`
- Plugin engine calls
- Plugin test support crate
- Official plugin template
=> Release notes 0.92 devyn (2)

book/plugins.md, contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
- `stream_example` removal
- `LabeledError` changes
- `GetHelp` engine call
- Plugin tests
- Plugin command API changes
=> Book docs for recent plugin changes

blog/2024-04-02-nushell_0_92.md
- Be a little more clear about what's changed with plugins from the beginning
- `into string` changes
- advice for upgrading (found some issues that can happen with `register` commands saved in `plugin.nu`)
- custom values examples
=> More little changes to the 0.92 release notes to cover things I did

blog/2024-04-02-nushell_0_92.md
- **More on perf, `into bits` explainer**
- **Rename perf section**
=> stefan release note

blog/2024-04-04-nushell_0_92_1.md
Documented the fixes included, added the changelog, and a warning about the breaking change I added by mistake.
=> Release notes 0.92.1 + breaking change

blog/2024-04-30-30k_blog.md
This PR is a small thank you to our users. Thank you for all you do!
=> the 30k star blog post

book/background_task.md
Easiler -> easier
and minor tweak to the sentence.
=> Update background_task.md : Minor typo fix

make_docs.nu
Fix make_docs.nu for Nu v0.93.0
=> fix: Fix make_docs.nu for Nu v0.93.0

book/dataframes.md
`dfr` is going to be deprecated in favor of the `polars` plugin.
I've written installation instructions and updated all the examples with `polars` using `numd`.
I'm preparing a draft PR to wait before all the decisions on `dfr` deprecation are made. I guess I will submit it closer to 0.94.
=> Dataframe chapter update

blog/2024-05-15-bashisms.md
A blog post about what bashisms are and which ones nushell supports.
=> bashism blog entry

book/overlays.md
Resolve https://github.com/nushell/nushell.github.io/issues/1407
=> fix: update export alias in overlays.md

blog/2024-05-28-nushell_0_94_0.md
Detail some of the changes plugin developers will have to deal with.
- API changes
- Protocol changes
=> Add some release notes targeted at plugin developers

book/cheat_sheet.md
for syntax highlighting
as discussed in PR #1425
=> Change inline code to code blocks

blog/2024-05-30-nushell_0_94_1.md
- nushell/nushell#12994
- nushell/nushell#13001
- nushell/nushell#13002
- nushell/nushell#13006
- nushell/nushell#13009
=> Release notes for `0.94.1`

book/coming_from_cmd.md
Please see https://github.com/nushell/nushell/issues/12642#issuecomment-2074738988
=> Replace `exit` with `dexit` for popd analog

package-lock.json, package.json
Upgrade shiki the syntax highlight plugin and lefthook, etc.
=> Upgrade shiki the syntax highlight plugin and lefthook, etc.

contributor-book/plugin_protocol_reference.md, contributor-book/plugins.md
=> Add `Metadata` to plugin protocol reference, and `version()` to the guide

blog/2024-06-25-nushell_0_95_0.md
* full changelog
* TODO items
* PR lists based on the `pr:*` labels
=> List PRs in the 0.95.0 release notes

blog/2024-06-25-nushell_0_95_0.md
by opening PRs against the `release-notes-0.95.0` branch.
=> Release notes for `0.95.0`

book/operators.md, de/book/operators.md, zh-CN/book/operators.md
Change the case sensitive option from '--insensitive' to '--ignore-case'.
=> Fix str contains case sensitive option

book/cheat_sheet.md
=> minor spelling mistake

book/dataframes.md
=> abbreviate the output in an example in dataframes to avoid a typo false positive

book/pipelines.md
This updates the `$in` documentation to reflect the improvements in https://github.com/nushell/nushell/pull/13357.
Hold for 0.96 - Review and improvements requested in the meantime.
=> Updates for 0.96 $in improvements

contributor-book/plugins.md
@fdncred - hopefully this helps fill that gap!
=> Add example for the new CallDecl engine call

blog/2024-07-29-nushell_0_96_1.md
by opening PRs against the `release-notes-0.96.1` branch.
=> Release notes for `0.96.1`

book/working_with_strings.md
Noticed that I was missing a comment character in one of the code-blocks.
=> Quick fix to String doc

cookbook/http.md
It was implemented in nushell/nushell#13532
=> Add docs for file uploads

book/coming_from_bash.md
Adds `each` and `for` Nushell examples for the Bash `for` command
Closes out #84 for sure ;-)
=> Bash `for` command mapping

blog/2024-08-20-nushell_0_97_0.md, blog/2024-08-20-nushell_0_97_1.md
by opening PRs against the `release-notes-0.97.0` branch.
=> Release notes for `0.97.1`

book/working_with_records.md
That was wrongly copied from the list equivalent
=> fix: copy paste mistake

blog/2024-09-04-discord-showcase.md
=> Blog announcement for Discord Showcase

.vuepress/configs/sidebar/en.ts, book/types_of_data.md, lang-guide/chapters/types/basic_types/datetime.md
=> Fix `datetime` annotation

make_docs.nu
=> Fix make_docs.nu for Nu v0.98

book/aliases.md, book/custom_completions.md, book/dataframes.md, book/pipelines.md, book/variables.md
After @132ikl's updates to the Modules chapter, I decided to check if there were any other blockquotes hanging around. Found and fixed a few more in other chapters.
=> Convert blockquotes to callouts

blog/2024-10-15-nushell_0_99_0.md
by opening PRs against the `release-notes-0.99.0` branch.
(https://github.com/nushell/nushell/labels/deprecation) or [removals](https://github.com/nushell/nushell/pulls?q=is%3Apr+is%3Aopen+label%3Aremoval-after-deprecation))
=> Release notes for `0.99.0`

book/coming_from_bash.md
Just because this seems like a super common use-case and it took me a little while to figure out how to do it as you don't get any hits for "secret" or "credential" when searching the website.
=> Updated Coming from Bash for reading a secret

CONTRIBUTING.md, book/dataframes.md, package-lock.json
Also:
- tidy/clarify contributing doc
- bump micromatch to address npm audit warning
=> Fix dataframe python example

book/modules/creating_modules.md
=> Fix typo in code example

book/3rdpartyprompts.md
* Use upstream name/brand formatting 'nerdfonts' -> 'Nerd Fonts'
* Describe/Mention what Nerd Fonts is
* Quote projects own description
* Use more descriptive web link labels
=> Improve Nerd Fonts docs

book/modules/creating_modules.md
Fixes the issue (for real, hopefully) in #1609 - See my comment there for details on why this is needed.
=> Fix Creating Modules code example (a bit further)

book/coming_from_cmd.md
Fix the command prepend to append in the coming from guide.
=> Fix prepend to append in coming_from_cmd.md

blog/2024-11-12-nushell_0_100_0.md
Update release note by scripts
=> Update release note by scripts

book/coming_from_cmd.md
=> Add missing cmd to nu command

book/coming_from_cmd.md
Follow-up to #1637 as per discussion
=> Use `in` for variable defined condition

.vuepress/styles/index.scss
Allow wider page contents, addressing #1661 and modify blog title color of light theme
=> Allow wider page content

blog/2024-12-24-nushell_0_101_0.md
The cool new `write-toc` command was slightly broken https://github.com/nushell/nu_scripts/pull/981
=> Fix release note anchors

lang-guide/chapters/custom_commands.md, lang-guide/chapters/declarations.md, lang-guide/chapters/filters/select-get.md, lang-guide/chapters/filters/selecting_data.md, lang-guide/chapters/filters/where-filter.md, lang-guide/chapters/flow_control/break.md, lang-guide/chapters/flow_control/continue.md, lang-guide/chapters/flow_control/loop.md, lang-guide/chapters/flow_control/match.md, lang-guide/chapters/flow_control/return.md, lang-guide/chapters/flow_control/try-catch.md, lang-guide/chapters/flow_control/while.md, lang-guide/chapters/functional_programming.md, lang-guide/chapters/helpers_and_debugging.md, lang-guide/chapters/metadata.md, lang-guide/chapters/strings.md, lang-guide/chapters/variable_scope.md
As per [discord discussion](https://discord.com/channels/601130461678272522/729071784321876040/1331412437714468884) to help exclude pages that shouldn't show up on search because they have no real content.
=> chore: add draft front matter for todo/placeholder pages

book/coloring_and_theming.md
* Explain `LS_COLORS` format
* Give examples
* Be more elaborate and give examples of using `vivid` and alternative themes
Resolves #1754
=> Fix and extend LS_COLORS documentation

blog/2025-02-04-nushell_0_102_0.md
by opening PRs against the `release-notes-0.102.0` branch.
=> Release notes for `0.102.0`

blog/2025-02-04-nushell_0_102_0.md
fix typo in flag `move --list`: change to `move --last`
=> fix typo in flag `move --list`: change to `move --last`

blog/2025-02-04-nushell_0_102_0.md
Closes #1788 - Also have fixed in the template so it shouldn't be an issue going forward, and @ysthakur has updated the future 0.103 already.
=> Update 0.102.0 release notes with plugin info

blog/2025-01-30-twin0284.md, blog/2025-02-08-twin0285.md
Adds "This Week in Nushell 285"
=> This Week in Nushell #285

blog/2025-02-14-twin0286.md
Fixes minor typo and adds a quick blurb about feedback.
=> Fix TWiN 286 typo

blog/2025-02-21-twin0287.md
=> Add Twin #0287

book/dataframes.md, book/testing.md, cookbook/jq_v_nushell.md, cookbook/pattern_matching.md, snippets/book/std_log.nu
=> Replace usages of use std

book/installation.md
Add deb, rpm and apk install guide
=> Add deb, rpm and apk install guide

book/navigating_structured_data.md
Sorry for nitpicking, this is just what I found during regular docs reading.
=> Fix grammar

blog/2025-02-28-twin0288.md
=> Added TWiN #288

book/coming_from_bash.md, zh-CN/book/coming_from_bash.md
- Adds `pwd` in the cook book when coming from bash.
- Refactor the chinese table.
=> Add `pwd` command

blog/2025-03-14-twin0290.md
This Week in Nushell, I posted This Week in Nushell
=> Added TWiN 290

blog/2025-03-21-twin0291.md
=> Added TWiN 291

de/README.md
PR #779 suggested a wording change that lead to some discussion about the wording. IMO the suggestion is neither a fixup nor an improvement.
As per discussion there, this PR suggests a significant improvement to the wording. With an emphasis on data being structured.
Replaces #779
=> Improve German landing page

book/environment.md, book/explore.md, de/book/environment.md, zh-CN/book/configuration.md, zh-CN/book/environment.md
Fix the link of default_env.nu and default_config.nu.
=> Fix broken links in configuration.md, environment.md and explore.md

book/working_with_records.md
=> Clarify immutability to avoid confusion

.vuepress/configs/sidebar/de.ts, .vuepress/configs/sidebar/en.ts
https://github.com/nushell/nushell.github.io/pull/1826#issuecomment-2780149239
=> Fix sidebar for background job article

contributor-book/plugins.md
=> Update Plugin example version numbers

blog/2025-04-25-twin0296.md
Oops - forgot to update it when I pushed initially.
=> Update/fix TWiN extract

.vuepress/styles/index.scss
Disable code block font ligatures.  Fixes #1921
=> Disable code block font ligatures

blog/2025-05-23-nushell_0_104_1.md
Initial commit of 0.104.1 release notes
=> Initial commit of 0.104.1 release notes
